Кальянов -- Лабораторная работа #2
UNN-ITMM-Software/agile-course-practice pull request #101
Opened 2019-12-12 18:57 UTC by KalyanovDO

2019-12-12 18:58 UTC, KalyanovDO commented
@AndrewSmrnv, @VladimirTyagunov, please, take a look.

2019-12-13 14:57 UTC, VladimirTyagunov commented
:+1:

2019-12-13 15:14 UTC, AndrewSmrnv commented
:+1:

2019-12-16 07:27 UTC, might52 commented on code/polygon-area/View/src/main/java/ru/unn/agile/polygon/view/CalcArea.java
> +        tablePoints.setItems(viewModel.getPointList());
Необходимо избавиться от прямого вызова методов из ViewModel.
ViewModel устанавливает и начальные значения и контролирует дальнейшую работу.
Смысл MVVM в этом и заключается. См. пример преподавателя.
См. пример исправления - https://github.com/UNN-ITMM-Software/agile-course-practice/pull/98
Подобная ошибка.

2019-12-16 07:29 UTC, might52 requested changes

2019-12-16 07:29 UTC, might52 commented on code/polygon-area/View/src/main/java/ru/unn/agile/polygon/view/CalcArea.java
> +        tablePoints.setItems(viewModel.getPointList());
Необходимо избавиться от прямого вызова методов из ViewModel.
ViewModel устанавливает и начальные значения и контролирует дальнейшую работу.
Смысл MVVM в этом и заключается. См. пример преподавателя.
См. пример исправления - #98
Подобная ошибка.

Иными словами нужно перейти на проперти.

2019-12-16 16:34 UTC, KalyanovDO commented on code/polygon-area/View/src/main/java/ru/unn/agile/polygon/view/CalcArea.java
> +        tablePoints.setItems(viewModel.getPointList());
Спасибо за комментарий, биндинг поправил.

2019-12-18 13:47 UTC, might52 approved these changes

2019-12-18 13:49 UTC, merged