Лапин -- Лабораторная работа #3
UNN-ITMM-Software/agile-course-practice pull request #105
Opened 2019-12-14 13:41 UTC by Regmir

2019-12-14 13:47 UTC, Regmir commented
@stepanshulpin , @karevboris поревьюйте пожалуйста

2019-12-21 00:39 UTC, karevboris requested changes

2019-12-21 00:39 UTC, karevboris commented on code/length-converter/Infrastructure/src/test/java/ru/unn/agile/converter/infrastructure/RegexMatcher.java
> +        //NOTE: this ugly cast is needed to workaround 'unchecked' Java warning
Комментарии - зло.)

2019-12-21 00:39 UTC, karevboris commented on code/length-converter/ViewModel/src/main/java/ru/unn/agile/converter/viewmodel/LengthConverterViewModel.java
> +            + "length type was changed to ";
Лучше полностью переносить текстовые строки - удобнее читать.

2019-12-21 09:57 UTC, karevboris approved these changes
👍

2019-12-21 16:48 UTC, stepanshulpin commented on code/length-converter/ViewModel/src/main/java/ru/unn/agile/converter/viewmodel/LengthConverterViewModel.java
> +            records += logString + "\n";
Стоит переделать в StringBuilder

2019-12-21 16:50 UTC, stepanshulpin commented on code/length-converter/ViewModel/src/main/java/ru/unn/agile/converter/viewmodel/LengthConverterViewModel.java
> +    public static final String INCORRECT_INPUT = "Incorrect input. ";
Помоему лишний пробел

2019-12-21 17:41 UTC, stepanshulpin commented
👍

2019-12-21 19:44 UTC, merged