Зырина -- Лабораторная работа #3
UNN-ITMM-Software/agile-course-practice pull request #108
Opened 2019-12-15 14:15 UTC by Selllavi

2019-12-15 15:14 UTC, Selllavi commented
@Yaroslav-Lahtachev , @ViolettaShirokikh  and again review it as the last time..

2019-12-16 17:22 UTC, ViolettaShirokikh commented on code/arabic-roman-converter/Infrastructure/src/test/java/ru/unn/agile/arabicromanconverter/infrastructure/RegexMatcher.java
> +        //NOTE: this ugly cast is needed to workaround 'unchecked' Java warning
remove comments

2019-12-16 17:22 UTC, ViolettaShirokikh commented on code/arabic-roman-converter/ViewModel/src/test/java/ru/unn/agile/arabicromanconverter/viewmodel/ArabicRomanConverterViewModelTests.java
> +    public void logContainsIncorrectValueAfteIncorrectInput() {
check the word "After" in Test name

2019-12-16 21:43 UTC, Selllavi commented
@ViolettaShirokikh  check, please

2019-12-17 06:58 UTC, ViolettaShirokikh commented
:+1:

2019-12-17 19:11 UTC, Yaroslav-Lahtachev commented
👍  The best lab that i have seen in my life, i can't imagine that i could do something like this.

2019-12-20 10:59 UTC, might52 requested changes

2019-12-20 10:59 UTC, might52 commented on code/arabic-roman-converter/Infrastructure/src/test/java/ru/unn/agile/arabicromanconverter/infrastructure/TxtLoggerTests.java
> +        } catch (FileNotFoundException e) {
Please use expect construction in @Test annotation instead of try/catch.

2019-12-20 14:15 UTC, might52 commented on code/arabic-roman-converter/Infrastructure/src/test/java/ru/unn/agile/arabicromanconverter/infrastructure/TxtLoggerTests.java
> +        } catch (FileNotFoundException e) {
after internal discussion agree with the current way

2019-12-20 14:16 UTC, might52 approved these changes

2019-12-20 17:22 UTC, merged