Лапин -- Лабораторная работа #0
UNN-ITMM-Software/agile-course-practice pull request #11
Opened 2019-11-02 11:53 UTC by Regmir

@karevboris

2019-11-02 12:13 UTC, Regmir commented
@stepanshulpin

2019-11-03 14:11 UTC, karevboris requested changes

2019-11-03 14:11 UTC, karevboris commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/LapinArtemTest.java
> +    }
Дублирование с public void getRealWorksCorrect().

2019-11-03 14:11 UTC, karevboris commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/LapinArtemTest.java
> +    }
Дублирование с public void getImagineWorksCorrect().

2019-11-03 14:44 UTC, Regmir commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/LapinArtemTest.java
> +    }
убрал дублирующиеся тесты

2019-11-03 15:24 UTC, karevboris reviewed
👍

2019-11-03 20:59 UTC, stepanshulpin commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/LapinArtemTest.java
> +        ComplexNumber addResult = cn1.multiply(cn2);
Let's use enum with operations

2019-11-03 21:45 UTC, stepanshulpin commented
👍

2019-11-03 22:01 UTC, stepanshulpin approved these changes

2019-11-04 05:35 UTC, vgvoleg requested changes

2019-11-04 05:35 UTC, vgvoleg commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/LapinArtemTest.java
> +        assertEquals(cn.toString(), "1.0 + 1.0i");
Первый аргумент это expected, а второй actual. У тебя в некоторых местах не так, в случае ошибок репорт будет читать проблематично

2019-11-04 05:35 UTC, vgvoleg commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/LapinArtemTest.java
> +        ComplexNumber addResult = MULTIPLY.apply(cn1, cn2);
productResult?

2019-11-04 05:35 UTC, vgvoleg commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/LapinArtemTest.java
> +        ComplexNumber addResult = ADD.apply(cn1, cn2);
Скорее всего это вкусовщина, но при использовании enum’ов чаще всего импортируют не сами значения, а enum. Соответственно, читать и воспринимать что к чему относится проще Operation.ADD, нежели просто ADD. Повторюсь, я не нашел строгих правил на этот счет и это замечание это скорее всего вкусовщина.

2019-11-04 08:41 UTC, Regmir commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/LapinArtemTest.java
> +        ComplexNumber addResult = ADD.apply(cn1, cn2);
Поправил все замечния

2019-11-04 09:35 UTC, vgvoleg approved these changes

2019-11-04 09:36 UTC, vgvoleg commented
👍

2019-11-04 09:55 UTC, Regmir commented
@kirill-korniakov

2019-11-10 19:51 UTC, merged