Гришин -- Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice pull request #112
Opened 2019-12-15 20:33 UTC by dmitrygeralt

2019-12-15 20:33 UTC, dmitrygeralt commented
@antonyvlasov332 @madamdarianafedorova Have a look

2019-12-15 20:50 UTC, antonyvlasov332 commented
👍

2019-12-15 21:27 UTC, madamdarianafedorova commented
👍

2019-12-16 10:54 UTC, vgvoleg requested changes

2019-12-16 10:54 UTC, vgvoleg commented on code/cross-sections/Model/src/main/java/ru/unn/agile/crosssections/model/CrossChecker.java
> +    public CrossChecker() {
Зачем?

2019-12-16 10:54 UTC, vgvoleg commented on code/cross-sections/Model/src/main/java/ru/unn/agile/crosssections/model/CrossChecker.java
> +public class CrossChecker {
У данного класса нет никакого контекста, соответственно его методы можно и нужно сделать статическими

2019-12-16 10:54 UTC, vgvoleg commented on settings.gradle
> +// Cross Sections
Не надо добавлять себя в конец, для твоей работы есть конкретная секция с твоим именем

2019-12-16 11:42 UTC, dmitrygeralt commented
@vgvoleg check again, please

2019-12-16 12:48 UTC, vgvoleg approved these changes

2019-12-16 12:48 UTC, merged