Федорова -- Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice pull request #113
Opened 2019-12-15 22:20 UTC by madamdarianafedorova

2019-12-15 22:21 UTC, madamdarianafedorova commented
Good night,
@dmitrygeralt , @antonyvlasov332 check my code:)

2019-12-15 22:23 UTC, dmitrygeralt commented
Well done :) 👍

2019-12-15 22:25 UTC, antonyvlasov332 commented
👍

2019-12-16 11:00 UTC, vgvoleg requested changes

2019-12-16 11:00 UTC, vgvoleg commented on code/currency-converter/Model/src/main/java/ru/unn/agile/currencyconverter/model/CurrencyConverter.java
> +    public double convert() {
Переделай пожалуйста на один единственный статический метод, нет никакой необходимости каждый раз инстанциировать конвертер

2019-12-16 11:00 UTC, vgvoleg commented on settings.gradle
> +// Currency Converter
Не надо добавлять себя в конец файла, для вас создали именные секции

2019-12-16 11:15 UTC, nik709 requested changes

2019-12-16 11:15 UTC, nik709 commented on code/currency-converter/Model/src/main/java/ru/unn/agile/currencyconverter/model/CurrencyConverter.java
> +        if (currency <= 0) {
Разве карренси не может равняться 0?

2019-12-16 11:15 UTC, nik709 commented on code/currency-converter/Model/src/main/java/ru/unn/agile/currencyconverter/model/CurrencyConverter.java
> +public class CurrencyConverter {
В совокупности со статикой (без инстанциирования конвертера) класс должен быть `final`, так как наследование от него не предполагается.

2019-12-16 11:15 UTC, nik709 commented on code/currency-converter/Model/src/main/java/ru/unn/agile/currencyconverter/model/CurrencyPair.java
> +    private double exchange;
Неизменяемые поля должны быть помечены как `final`

2019-12-16 11:15 UTC, nik709 commented on code/currency-converter/Model/src/main/java/ru/unn/agile/currencyconverter/model/ExchangeRates.java
> +public final class ExchangeRates {
Все поля класса имеют видимость на уровне пакета, а сам класс доступен везде.
Действительно ли класс `public`? Предлагаю сделать`package-private`.

2019-12-16 11:53 UTC, madamdarianafedorova commented
@nik709, @vgvoleg

2019-12-16 12:07 UTC, nik709 commented
👍

2019-12-16 12:47 UTC, vgvoleg requested changes

2019-12-16 12:47 UTC, vgvoleg commented on code/currency-converter/Model/src/test/java/ru/unn/agile/currencyconverter/model/CurrencyConverterTest.java
> +        var expectedDollar = 112.00000000000001;
Зачем?

2019-12-16 12:50 UTC, madamdarianafedorova commented on code/currency-converter/Model/src/test/java/ru/unn/agile/currencyconverter/model/CurrencyConverterTest.java
> +        var expectedDollar = 112.00000000000001;
Такой результат конвертации

2019-12-16 12:54 UTC, madamdarianafedorova commented on code/currency-converter/Model/src/test/java/ru/unn/agile/currencyconverter/model/CurrencyConverterTest.java
> +        var expectedDollar = 112.00000000000001;
Но так как в сравнении есть delta можно оставить просто 112. Я убрала остаток.

2019-12-16 13:09 UTC, vgvoleg approved these changes

2019-12-16 13:09 UTC, merged