Шульпин -- Лабораторная работа #3
UNN-ITMM-Software/agile-course-practice pull request #115
Opened 2019-12-16 21:09 UTC by stepanshulpin

2019-12-16 21:09 UTC, stepanshulpin commented
@Regmir , @karevboris please review

2019-12-17 21:20 UTC, VitKonevskiy commented on code/quadratic-equation/Infrastructure/src/main/java/ru/unn/agile/quadraticequation/infrastructure/QuadraticEquationTxtLogger.java
> +    private static final String DATE_FORMAT_NOW = "yyyy-MM-dd HH:mm:ss";
Может лучше yyyy-MM-dd HH:mm:ss.SSS ?

2019-12-17 21:20 UTC, VitKonevskiy commented on code/quadratic-equation/Infrastructure/src/main/java/ru/unn/agile/quadraticequation/infrastructure/QuadraticEquationTxtLogger.java
> +            writer.write(now() + " > " + s);
Пожалуй, лучше разделитель вынести как константу и использовать String.format()

2019-12-17 21:20 UTC, VitKonevskiy commented on code/quadratic-equation/ViewModel/src/test/java/ru/unn/agile/quadraticequation/viewmodel/QuadraticEquationViewModelTest.java
> +                + "Result" + ".*"));
На одной строке смотрелось бы лаконичнее :)

2019-12-17 21:20 UTC, VitKonevskiy commented on code/quadratic-equation/ViewModel/src/main/java/ru/unn/agile/quadraticequation/viewmodel/QuadraticEquationILogger.java
> +
Полагаю, для поддержки единого стиля, лучше удалить пустую строку

2019-12-21 00:46 UTC, karevboris requested changes

2019-12-21 00:46 UTC, karevboris commented on code/quadratic-equation/Infrastructure/src/test/java/ru/unn/agile/quadraticequation/infrastructure/RegexMatcher.java
> +        //NOTE: this ugly cast is needed to workaround 'unchecked' Java warning
Надо убрать комментарий.

2019-12-21 00:46 UTC, karevboris commented on code/quadratic-equation/ViewModel/src/test/java/ru/unn/agile/quadraticequation/viewmodel/QuadraticEquationViewModelTest.java
> +    public void argumentsInfoIssProperlyFormatted() {
Опечатка.

2019-12-21 19:19 UTC, Regmir commented
👍

2019-12-21 19:23 UTC, karevboris approved these changes
👍

2019-12-21 19:37 UTC, merged