Гришин -- Лабораторная работа #2
UNN-ITMM-Software/agile-course-practice pull request #116
Opened 2019-12-16 21:32 UTC by dmitrygeralt

2019-12-16 21:32 UTC, dmitrygeralt commented
@madamdarianafedorova , @antonyvlasov332  see my new cool code

2019-12-16 21:52 UTC, antonyvlasov332 commented
👍

2019-12-17 16:25 UTC, madamdarianafedorova commented
👍

2019-12-19 11:59 UTC, vgvoleg requested changes

2019-12-19 11:59 UTC, vgvoleg commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +        assertEquals("", viewModel.getInputCurrency().get());
один тест - один ассерт

2019-12-19 17:34 UTC, madamdarianafedorova commented
@vgvoleg  check again, please

2019-12-19 17:37 UTC, dmitrygeralt commented
@vgvoleg

2019-12-19 19:17 UTC, vgvoleg requested changes

2019-12-19 19:17 UTC, vgvoleg commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +    public void canSetEmptyStringInInputByDefault() {
Странная формулировка в названии. Что значит can? Типа может засетить, а может и не засетить?

2019-12-19 19:48 UTC, dmitrygeralt commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +    public void canSetEmptyStringInInputByDefault() {
Проверка, что может засетить.  
Тут же не CanOrCannot. 
Даже в лабе примера было 
canSetEmpty ru.unn.agile.ComplexNumber.viewmodel.ViewModelTests#canSetDefaultValues
Название по Clean Code, глагол, подчеркивает одну конкретную функциональность "подстановки пустой стринги в инпут по умолчанию", что в тесте и проверяется.

2019-12-19 20:01 UTC, vgvoleg commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +    public void canSetEmptyStringInInputByDefault() {
Плохой референс на ComplexNumber. Там джавовские пакеты были названы с большой буквы.
Конкретная функциональность «подстановки пустой стринги в инпут по умолчанию» это setsEmptyStingToInputByDefault, глагол can здесь не нужен. Переименуй.

2019-12-19 20:10 UTC, dmitrygeralt commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +    public void canSetEmptyStringInInputByDefault() {
Да хорошо, я переименовал

2019-12-19 20:15 UTC, vgvoleg requested changes

2019-12-19 20:15 UTC, vgvoleg commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +    public void canSetEmptyStringInInputByDefault() {
Мне под каждым аналогичным тестом написать замечание, или ты сам сможешь переименовать все похожие места?

2019-12-19 20:24 UTC, dmitrygeralt commented
Я конечно поправил, но как насчет такого примера?
ru.unn.agile.polynomialcalculator.model.PolynomialTest#canInitZeroPolynomial
ru.unn.agile.polynomialcalculator.model.PolynomialTest#cannotCreatePolynomialWithNegativeDegree
ru.unn.agile.polynomialcalculator.model.PolynomialTest#canCreatePolynomialWithNonZeroCoefAndDegree

2019-12-19 20:28 UTC, vgvoleg requested changes

2019-12-19 20:28 UTC, vgvoleg commented on code/korniakov-kirill-lab2/ViewModel/src/test/java/ru/unn/agile/ComplexNumber/viewmodel/ViewModelTests.java
> +    public void setsEmptyStingToInputByDefault() {
Не надо трогать чужие проекты.

2019-12-19 20:28 UTC, vgvoleg commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +        assertEquals(CurrencyPair.values()[5], viewModel.getCurrencyPairs().get(5));
Тесты должны содержать в названии утверждение, а не вопрос. Читаются они следующим образом: Название класса (существительное) - утверждение (включая глагол). Калькулятор может складывать числа. Поле не содержит ошибок. И так далее. У тебя несколько тестов не подходит под это правило. Исправь. 
А еще я не совсем понимаю что делает этот тест. Проверяет длины(судя из названия)? Проверяет пятые элементы? Что?

2019-12-19 20:28 UTC, vgvoleg commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +    public void canSetRubleToEuroInCurrencyPair() {
Ты уверен что тебе нужно 5 одинаковых по существу теста на каждое значение енума?

2019-12-19 20:28 UTC, vgvoleg commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +    public void canConvert() {
can convert что? Следующие тесты в названии несут какую-то конкретку, этот - нет. Укажи что может конвертировать из такой-то валюты в такую-то по дефолту

2019-12-19 20:30 UTC, dmitrygeralt commented on code/korniakov-kirill-lab2/ViewModel/src/test/java/ru/unn/agile/ComplexNumber/viewmodel/ViewModelTests.java
> +    public void setsEmptyStingToInputByDefault() {
я уже откатил просто гитхаб так отображает до сих пор. 
Бага гитхаба, в UI при нажатии реактирования, все еще canSetDefaultValues.

2019-12-19 20:34 UTC, vgvoleg commented
> Я конечно поправил, но как насчет такого примера?
> ru.unn.agile.polynomialcalculator.model.PolynomialTest#canInitZeroPolynomial
> ru.unn.agile.polynomialcalculator.model.PolynomialTest#cannotCreatePolynomialWithNegativeDegree
> ru.unn.agile.polynomialcalculator.model.PolynomialTest#canCreatePolynomialWithNonZeroCoefAndDegree

Я ценю твое рвение поспорить, но ты сейчас сравниваешь *библиотеку*, которая должна *уметь* предоставить возможность использовать ее как угодно, с *вьюхой*, которая не спрашивает пользователя какими значениями ей надо проинициализировать поля по умолчанию. Она не *может* сделать так, она *обязана* (по вашему контракту) сделать так. Поэтому тест ты называешь не можетЗасетитьПустуюСтрокуПоУмолчанию, а сетитПустуюСтрокуПоУмолчанию.

2019-12-19 20:40 UTC, dmitrygeralt commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +    public void canSetRubleToEuroInCurrencyPair() {
Да, потому что я хочу 100% покрытие функционала.
Если бы я сделал только на одно, ты бы сказал почему здесь не все 5?

2019-12-19 20:44 UTC, dmitrygeralt commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +    public void canConvert() {
поменял название

2019-12-19 20:44 UTC, dmitrygeralt commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +        assertEquals(CurrencyPair.values()[5], viewModel.getCurrencyPairs().get(5));
поменял тест полностью

2019-12-19 20:45 UTC, vgvoleg commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +    public void canConvert() {
Плохо поменял

2019-12-19 20:50 UTC, dmitrygeralt commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +    public void canConvert() {
а так?

2019-12-19 20:54 UTC, vgvoleg commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +    public void canConvert() {
Тоже плохо. Подсказка: чтобы не переделывать еще раз, можно прочитать мое замечание

2019-12-19 21:01 UTC, dmitrygeralt commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +    public void canConvert() {
А теперь?

2019-12-19 21:09 UTC, vgvoleg commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +        assertEquals(CurrencyPair.values()[5], viewModel.getCurrencyPairs().get(5));
Обрати внимание на абзац побольше. У тебя остались тесты с плохими названиями

2019-12-20 08:26 UTC, dmitrygeralt commented
Почему ты смержил Андрея например с canSet неймингами во всех тестах во второй лабе? И не только canSet они все начинаются с can.
Во вьюхе, не в библиотеке. Как ты написал в комментарии выше это не приемлимо.

https://github.com/UNN-ITMM-Software/agile-course-practice/pull/100/files#diff-9e6518c4dbcbb0b389c10fe45490a4dcR29

Тем не менее никаких замечаний к нему у тебя не было. А меня ты заставил поменять на sets все это, я поменял и теперь эта эпопея продолжается.
А с меня ты уже спрашиваешь 10ый раз "переименуй имена тестов, так как хочу я, но как я хочу, я тебе не скажу". 
Выглядит как бесконечная игра в шарады. 

>> Обрати внимание на абзац побольше. У тебя остались тесты с плохими названиями
Внимание абзац
>> Тесты должны содержать в названии утверждение, а не вопрос. Читаются они следующим образом: Название класса (существительное) - утверждение (включая глагол). Калькулятор может складывать числа. Поле не содержит ошибок. И так далее. У тебя несколько тестов не подходит под это правило. Исправь.

Никакой конкретики. Никаких примеров что и как по твоему лучше переименовать.
Да и то я попытался исправить абсолютно все тесты как ты и просил. 
Теперь продолжаем игру в шарады, если твой абцаз значил что все тесты должны начинаться с глаголов, почему ты сам писал начиная с существительных?

https://github.com/vgvoleg/agile-course-practice/blob/d6f11fee5952693f362a6ed6edf690cac369e8e1/code/polynomialcalculator/src/test/java/ru/unn/agile/polynomialcalculator/model/PolynomialTest.java#L217

Да и ты смержил уже овер 10 человек с тестами где наименования начинаются на существительные. 

Я думаю это врятли хоть когда нибудь закончится, так как по существу есть мнение твое и неправильное. И твое меняется от человека к человеку, в зависимости от личной приязни.  
Мы тут учимся писать по Clean Code или удовлетворять все желания одного конкретного ревьювера?

2019-12-20 09:17 UTC, vgvoleg requested changes

2019-12-20 09:17 UTC, vgvoleg commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +    public void errorAfterIncorrectInput() {
hasErrorAfterIncorrectInput

2019-12-20 09:17 UTC, vgvoleg commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +    public void noErrorAfterCorrectInput() {
hasNoErrorAfterCorrectInput

2019-12-20 09:17 UTC, vgvoleg commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +    public void noErrorByDefault() {
hasNoErrorByDefault

2019-12-20 09:17 UTC, vgvoleg commented on code/currency-converter/ViewModel/src/test/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModelTests.java
> +    public void noErrorAfterClearInput() {
hasNoErrorAfterClearInput

2019-12-20 09:21 UTC, vgvoleg commented
> Почему ты смержил Андрея например с canSet неймингами во всех тестах во второй лабе? И не только canSet они все начинаются с can.
> Во вьюхе, не в библиотеке. Как ты написал в комментарии выше это не приемлимо.
> 
> https://github.com/UNN-ITMM-Software/agile-course-practice/pull/100/files#diff-9e6518c4dbcbb0b389c10fe45490a4dcR29
> 
> Тем не менее никаких замечаний к нему у тебя не было. А меня ты заставил поменять на sets все это, я поменял и теперь эта эпопея продолжается.
> А с меня ты уже спрашиваешь 10ый раз "переименуй имена тестов, так как хочу я, но как я хочу, я тебе не скажу".
> Выглядит как бесконечная игра в шарады.
> 
> > > Обрати внимание на абзац побольше. У тебя остались тесты с плохими названиями
> > > Внимание абзац
> > > Тесты должны содержать в названии утверждение, а не вопрос. Читаются они следующим образом: Название класса (существительное) - утверждение (включая глагол). Калькулятор может складывать числа. Поле не содержит ошибок. И так далее. У тебя несколько тестов не подходит под это правило. Исправь.
> 
> Никакой конкретики. Никаких примеров что и как по твоему лучше переименовать.
> Да и то я попытался исправить абсолютно все тесты как ты и просил.
> Теперь продолжаем игру в шарады, если твой абцаз значил что все тесты должны начинаться с глаголов, почему ты сам писал начиная с существительных?
> 
> https://github.com/vgvoleg/agile-course-practice/blob/d6f11fee5952693f362a6ed6edf690cac369e8e1/code/polynomialcalculator/src/test/java/ru/unn/agile/polynomialcalculator/model/PolynomialTest.java#L217
> 
> Да и ты смержил уже овер 10 человек с тестами где наименования начинаются на существительные.
> 
> Я думаю это врятли хоть когда нибудь закончится, так как по существу есть мнение твое и неправильное. И твое меняется от человека к человеку, в зависимости от личной приязни.
> Мы тут учимся писать по Clean Code или удовлетворять все желания одного конкретного ревьювера?

У тебя в купленной лабе правки тоже платные чтоли? Хорошо, поберегу твои деньги, я расписал оставшиеся правки, которые надо сделать. К сожалению, я пытался сэкономить твои деньги, но тест canConvert превратился в желаемый convertsRubleToDollarByDefault (после замечания "Укажи что может конвертировать из такой-то валюты в такую-то по дефолту") за 3 коммита

2019-12-20 10:09 UTC, dmitrygeralt commented
Олег, почему ты решил перевести тему? 
И закидываться необоснованными наездами? 
Потому что ты предлагал купить лабу у тебя, а я отказался? 
Может быть еще и ревью у тебя надо было покупать? 
И все же ты решил предоставить "правильные варианты" для названий тестов "чтобы угодить тебе"? 

Неужели откровенный стеб в ревью уже не такой веселый,
когда на это обратил внимание преподаватель? 

Насчет того теста да, потому что ведь для тебя варианты
>> canConvert()
>> converts()
>> convertsWithDefaultValues()
>> convertsWithDefaultCurrencyPair()

Это не по Clean Code названия, потому что тут же нет креативности в названиях, должно быть именно так как ты сказал и никак иначе.

Зато у Андрея canCalculate() тебе понравился сразу же, а меня ты заставил переделывать этот тест 4 раза пока он не стал в точности дословно таким как ты хотел.

https://github.com/might52/agile-course-practice/blob/9b81aba3ba35ab70827237cede06d653ec2943ae/code/deposit-calculator/viewmodel/src/test/java/ru/unn/agile/depositcalculator/viewmodel/ViewModelTest.java#L49

Тоесть ты не отрицаешь, что ты предвзято докапывался в течении 20 комментариев абсолютно не обоснованно и не давал никакой конкретики, просто потому, что ты "подумал", что я делал лабу не сам? 
И это оправдывает тебя как ревьювера? 
Сколько еще таких людей будет, что ты решишь засудить?
Можно спорить бесконечно и тратить дальше время в комментариях, но это не доставляет никакого удовольствия.  

Своим последним комментарием ты уже сам себя заложил, что твоя оценка как мержера предвзятая и обоснована только на личных предпочтениях и теориях о купленных - не купленных лабах. Зато своих одногруппников и друзей ты мержить без единой претензии.

2019-12-21 09:29 UTC, vgvoleg approved these changes

2019-12-21 09:29 UTC, merged