Симонян -- Лабораторная работа #3
UNN-ITMM-Software/agile-course-practice pull request #123
Opened 2019-12-18 08:05 UTC by Vagik

2019-12-20 09:25 UTC, nik709 requested changes

2019-12-20 09:25 UTC, nik709 commented on code/deposit-calculator/viewmodel/src/main/java/ru/unn/agile/depositcalculator/viewmodel/ViewModel.java
> +    public static final String PERIOD_UPDATED_LOG_MSG =
Предлагаю для месседжей логгера создать отдельный статичный класс

2019-12-20 09:25 UTC, nik709 commented on code/deposit-calculator/viewmodel/src/main/java/ru/unn/agile/depositcalculator/viewmodel/ViewModel.java
> +        return logger.getLog();
`NPE` в случае, если `ViewModel` была создана с помощью конструктора по умолчанию и не был вызван метод `setLogger`.
Предлагаю возвращать пустой лист в случае, если `logger == null`

2019-12-20 09:25 UTC, nik709 commented on code/deposit-calculator/viewmodel/src/main/java/ru/unn/agile/depositcalculator/viewmodel/ViewModel.java
> +        var fullLog = logger.getLog();
NPE + можно воспользоваться методов `ViewModel::getLogs`, когда поправишь предыдущий комментарий

2019-12-21 09:29 UTC, Vagik commented on code/deposit-calculator/viewmodel/src/main/java/ru/unn/agile/depositcalculator/viewmodel/ViewModel.java
> +    public static final String PERIOD_UPDATED_LOG_MSG =
Создал

2019-12-21 09:29 UTC, Vagik commented on code/deposit-calculator/viewmodel/src/main/java/ru/unn/agile/depositcalculator/viewmodel/ViewModel.java
> +        return logger.getLog();
Согласен, учёл комментарий

2019-12-21 09:29 UTC, Vagik commented on code/deposit-calculator/viewmodel/src/main/java/ru/unn/agile/depositcalculator/viewmodel/ViewModel.java
> +        var fullLog = logger.getLog();
Готово

2019-12-21 09:49 UTC, Vagik commented
@nik709 @VitKonevskiy @might52 , please review

2019-12-21 11:50 UTC, nik709 commented
👍

2019-12-21 16:15 UTC, might52 commented
:+1:

2019-12-21 18:50 UTC, merged