Попков -- Лабораторная работа #2
UNN-ITMM-Software/agile-course-practice pull request #124
Opened 2019-12-18 18:03 UTC by Ravie

2019-12-20 16:14 UTC, antonyvlasov332 commented on code/prime-number/View/src/main/java/ru/unn/agile/PrimeNumber/view/PrimeNumber.java
> +        // Two-way binding hasn't supported by FXML yet, so place it in code-behind
remove comment

2019-12-20 16:14 UTC, antonyvlasov332 commented on code/prime-number/ViewModel/src/main/java/ru/unn/agile/PrimeNumber/viewmodel/ViewModel.java
> +        return calculationDisabled;
why calculation? It is finding.

2019-12-20 16:14 UTC, antonyvlasov332 commented on code/prime-number/ViewModel/src/test/java/ru/unn/agile/PrimeNumber/viewmodel/ViewModelTests.java
> +        assertEquals("", viewModel.startElemProperty().get());
One test = one Assert

2019-12-20 16:14 UTC, antonyvlasov332 commented on code/prime-number/ViewModel/src/main/java/ru/unn/agile/PrimeNumber/viewmodel/ViewModel.java
> +        final List<StringProperty> fields = new ArrayList<>() {
It will be better to make it global private field and use it instead of startElement, endElement

2019-12-20 16:14 UTC, antonyvlasov332 commented on code/prime-number/ViewModel/src/main/java/ru/unn/agile/PrimeNumber/viewmodel/ViewModel.java
> +        // Add listeners to the input text fields
remove comment

2019-12-20 16:14 UTC, antonyvlasov332 commented on code/prime-number/ViewModel/src/main/java/ru/unn/agile/PrimeNumber/viewmodel/ViewModel.java
> +            outputField.set(stringJoiner.toString());
why not just primeNumsList .toString() ?

2019-12-21 00:56 UTC, Ravie commented on code/prime-number/View/src/main/java/ru/unn/agile/PrimeNumber/view/PrimeNumber.java
> +        // Two-way binding hasn't supported by FXML yet, so place it in code-behind
ok

2019-12-21 15:47 UTC, antonyvlasov332 commented
:+1:

2019-12-21 16:05 UTC, madamdarianafedorova commented
👍

2019-12-21 18:58 UTC, VitKonevskiy requested changes

2019-12-21 18:58 UTC, VitKonevskiy commented on code/prime-number/View/src/main/java/ru/unn/agile/PrimeNumber/view/Main.java
> +package ru.unn.agile.PrimeNumber.view;
please, use low case for package naming

2019-12-21 18:58 UTC, VitKonevskiy commented on code/prime-number/ViewModel/src/main/java/ru/unn/agile/PrimeNumber/viewmodel/ViewModel.java
> +package ru.unn.agile.PrimeNumber.viewmodel;
Also here

2019-12-21 18:58 UTC, VitKonevskiy commented on code/prime-number/ViewModel/src/main/java/ru/unn/agile/PrimeNumber/viewmodel/ViewModel.java
> +    }
Could you move this enum to separate java file, please

2019-12-21 18:58 UTC, VitKonevskiy commented on code/prime-number/ViewModel/src/test/java/ru/unn/agile/PrimeNumber/viewmodel/ViewModelTests.java
> +package ru.unn.agile.PrimeNumber.viewmodel;
And here

2019-12-22 07:29 UTC, VitKonevskiy approved these changes

2019-12-22 07:29 UTC, merged