lab 2
UNN-ITMM-Software/agile-course-practice pull request #125
Opened 2019-12-18 18:28 UTC by antonyvlasov332

2019-12-18 18:41 UTC, antonyvlasov332 commented
@madamdarianafedorova @dmitrygeralt

2019-12-18 19:18 UTC, dmitrygeralt commented
:+1:

2019-12-18 20:53 UTC, madamdarianafedorova commented
👍

2019-12-19 21:32 UTC, vgvoleg requested changes

2019-12-19 21:32 UTC, vgvoleg commented on code/cross-sections/Model/src/main/java/ru/unn/agile/crosssections/model/Dot.java
> +        this.x = Integer.parseInt(x);
Лучше воспользоваться базовым конструктором, то есть внутри текущего распарсить инты и передать в базовый

2019-12-19 21:32 UTC, vgvoleg commented on code/cross-sections/ViewModel/src/main/java/ru/unn/agile/crosssections/viewmodel/ViewModel.java
> +        final List<StringProperty> fields = new ArrayList<StringProperty>() {
Пользуйся этим списком, когда делаешь одинаковые действия с каждым из элементов. Операции по 8 строчек смотрятся плохо.

2019-12-19 21:32 UTC, vgvoleg commented on code/cross-sections/ViewModel/src/main/java/ru/unn/agile/crosssections/viewmodel/ViewModel.java
> +    public final boolean isCheckDisabled() {
Этот метод не используется. А зря. Я бы оставил его вместо получения объекта BooleanProperty

2019-12-19 21:32 UTC, vgvoleg commented on code/cross-sections/ViewModel/src/main/java/ru/unn/agile/crosssections/viewmodel/ViewModel.java
> +    private boolean isIncorrectInput(final StringProperty property) {
Обычно методы подобные методы проверяют на корректность, а не наоборот) лучше переделать на isInputCorrect

2019-12-21 09:28 UTC, vgvoleg approved these changes

2019-12-21 09:28 UTC, merged