Гришин -- Лабораторная работа #3
UNN-ITMM-Software/agile-course-practice pull request #134
Opened 2019-12-22 12:56 UTC by dmitrygeralt

2019-12-22 13:15 UTC, dmitrygeralt commented
@Ravie @antonyvlasov332  @madamdarianafedorova  review please

2019-12-22 16:43 UTC, madamdarianafedorova commented
👍

2019-12-22 17:09 UTC, VitKonevskiy requested changes

2019-12-22 17:09 UTC, VitKonevskiy commented on code/prime-number/Infrastructure/src/main/java/ru/unn/agile/primenumber/infrastructure/ActionLogger.java
> +    private static final String DATE_FORMAT = "yyyy-MM-dd HH:mm:ss";
I think "yyyy-MM-dd HH:mm:ss.SSS" should be more usefull

2019-12-22 17:09 UTC, VitKonevskiy commented on code/prime-number/Infrastructure/src/main/java/ru/unn/agile/primenumber/infrastructure/ActionLogger.java
> +            this.writer.write(now() + " ~~~ " + logMessage);
Pls, move separator to constant

2019-12-22 17:09 UTC, VitKonevskiy commented on code/prime-number/ViewModel/src/main/java/ru/unn/agile/primenumber/viewmodel/LogTemplates.java
> +    private LogTemplates() {
Pls, remove empty constructor

2019-12-22 19:18 UTC, vgvoleg commented on code/prime-number/ViewModel/src/main/java/ru/unn/agile/primenumber/viewmodel/LogTemplates.java
> +    private LogTemplates() {
он приватный, тут можно

2019-12-23 14:26 UTC, dmitrygeralt commented on code/prime-number/ViewModel/src/main/java/ru/unn/agile/primenumber/viewmodel/LogTemplates.java
> +    private LogTemplates() {
И если его убрать то упадет чекстайл :)
Utility classes should not have a public or default constructor. [HideUtilityClassConstructor]

2019-12-23 18:14 UTC, antonyvlasov332 commented
👍

2019-12-23 20:11 UTC, VitKonevskiy approved these changes

2019-12-23 20:11 UTC, merged