Федорова -- Лабораторная работа #3
UNN-ITMM-Software/agile-course-practice pull request #136
Opened 2019-12-22 16:50 UTC by madamdarianafedorova

2019-12-22 16:50 UTC, madamdarianafedorova commented
@Ravie, @dmitrygeralt,  @antonyvlasov332 check please :)

2019-12-22 18:02 UTC, antonyvlasov332 commented
👍

2019-12-23 14:25 UTC, dmitrygeralt commented
👍

2019-12-23 17:36 UTC, might52 requested changes

2019-12-23 17:36 UTC, might52 commented on code/cross-sections/Infrastructure/src/main/java/ru/unn/agile/crosssections/infrastructure/FileLogger.java
> +    @Override public List<String> getLog() {
@Override аннотация должна быть на методом не в его объявлении.

2019-12-23 17:36 UTC, might52 commented on code/cross-sections/Infrastructure/src/test/java/ru/unn/agile/crosssections/infrastructure/FileLoggerTest.java
> +    public void logMessage() {
Необходимо давать осмысленные названия тестам, 
logMessage не готовит, конкретно, что проверяется. 
canWriteLogMessage... - более подходящее.
Та же ситуация и с другим тестом.

2019-12-23 17:36 UTC, might52 commented on code/cross-sections/ViewModel/src/main/java/ru/unn/agile/crosssections/viewmodel/ViewModel.java
> +        return logger.getLog();
Общая ошибка у многих ребят, если будет инициализация с конструктором по умолчанию будет нулл поинтер в этом месте.
Есть два пути:
1. Добавить обработку.
2. Исключить возникновение узкого места.

2019-12-23 17:36 UTC, might52 commented on code/cross-sections/ViewModel/src/test/java/ru/unn/agile/crosssections/viewmodel/ViewModelTests.java
> +    public void getsEmptyLogAfterCreation() {
То же пример не совсем удачного именования теста:
Может получить пустой лог после создания более подходящий вариант. 

Посмотри почти на все имена тестов в этом файле. Они имеют некорректное именование.

2019-12-23 21:28 UTC, madamdarianafedorova commented
@might52 Поправила все замечания)

2019-12-23 21:29 UTC, might52 approved these changes

2019-12-23 21:30 UTC, merged