Власов -- Лабораторная работа #3
UNN-ITMM-Software/agile-course-practice pull request #137
Opened 2019-12-22 18:09 UTC by antonyvlasov332

2019-12-22 18:11 UTC, antonyvlasov332 commented
@madamdarianafedorova  @dmitrygeralt  @Ravie Hello, colleagues, do review again.

2019-12-23 14:24 UTC, dmitrygeralt commented
👍

2019-12-23 17:47 UTC, madamdarianafedorova commented
👍

2019-12-23 18:48 UTC, might52 requested changes

2019-12-23 18:48 UTC, might52 commented on code/range/ViewModel/src/main/java/ru/unn/agile/range/viewmodel/ViewModel.java
> +        return logger.getLog();
Общая ошибка у многих ребят, если будет инициализация с конструктором по умолчанию будет нулл поинтер в этом месте.
Есть два пути:
1. Добавить обработку.
2. Исключить возникновение узкого места.

2019-12-23 21:37 UTC, might52 approved these changes

2019-12-23 21:38 UTC, merged