Попков -- Лабораторная работа #3
UNN-ITMM-Software/agile-course-practice pull request #144
Opened 2019-12-24 18:00 UTC by Ravie

2019-12-24 18:09 UTC, Ravie commented
@antonyvlasov332 @madamdarianafedorova welcome to review my code=)

2019-12-24 20:02 UTC, madamdarianafedorova commented
👍

2019-12-24 20:03 UTC, dmitrygeralt commented
👍

2019-12-25 07:20 UTC, might52 requested changes

2019-12-25 07:20 UTC, might52 commented on code/currency-converter/ViewModel/src/main/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModel.java
> +            addToLog("Convert " + oldValue + " was changed by " + newValue);
Не совсем понятно почему в этому случае событие лога добавляется в листенер, а не в вызываемый метод. 
Сравни с другим случаем (convert()), приведи к единому виду.

2019-12-25 07:20 UTC, might52 commented on code/currency-converter/ViewModel/src/main/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModel.java
> +            addToLog("Input is incorrect!");
Вынеси в статические переменные сообщения об ошибках (лучше даже утилитный класс) и скорректируй тесты на использование этих же переменных.

2019-12-25 07:20 UTC, might52 commented on code/currency-converter/ViewModel/src/main/java/ru/unn/agile/currencyconverter/viewmodel/CurrencyConverterViewModel.java
> +            addToLog("Input is correct!");
Вынеси в статические переменные сообщения об ошибках (лучше даже утилитный класс) и скорректируй тесты на использование этих же переменных.

2019-12-25 08:49 UTC, might52 approved these changes

2019-12-25 08:56 UTC, merged