Смирнов -- Лабораторная работа #3
UNN-ITMM-Software/agile-course-practice pull request #145
Opened 2019-12-24 18:34 UTC by AndrewSmrnv

@KalyanovDO, @VladimirTyagunov , please review

2019-12-24 18:56 UTC, AndrewSmrnv commented
![Polygon Area Calculator](https://user-images.githubusercontent.com/43618538/71423138-3425d300-2698-11ea-8d6e-0e24bccc58bb.gif)
![Polygon Area Calculator failed](https://user-images.githubusercontent.com/43618538/71423139-3425d300-2698-11ea-9036-77dbc13213a2.gif)

2019-12-24 19:06 UTC, VladimirTyagunov commented
everything is 👌  
nice gif, by the way 👍 
👍

2019-12-24 19:06 UTC, KalyanovDO commented
:+1:

2019-12-25 08:47 UTC, might52 requested changes

2019-12-25 08:47 UTC, might52 commented on code/polygon-area/Infrastructure/src/test/java/ru/unn/agile/polygon/infrastructure/TxtLoggerTests.java
> +        File f = new File(LOG_FILE_PATH);
В чем суть этого теста?
Проверить стандартное API Java? ))
Удали, либо перепиши на использование логгера для создания файла.

2019-12-25 09:22 UTC, might52 approved these changes

2019-12-25 09:23 UTC, merged