Кулыгина -- Лабораторная работа #3
UNN-ITMM-Software/agile-course-practice pull request #146
Opened 2019-12-25 12:59 UTC by KulyginaJulia

2019-12-25 13:16 UTC, KulyginaJulia commented
@Anna-Mironova, @SemyonBevzuk, please review

2019-12-25 13:18 UTC, SemyonBevzuk commented
👍

2019-12-25 13:33 UTC, Anna-Mironova commented
👍

2019-12-25 14:44 UTC, KulyginaJulia commented
@vgvoleg, @VitKonevskiy, @might52, проревьюйте, пожалуйста

2019-12-26 07:21 UTC, might52 requested changes

2019-12-26 07:21 UTC, might52 commented on code/statistics-calculation/ViewModel/src/main/java/ru/unn/agile/StatisticsCalculation/viewmodel/ViewModel.java
> +        return logger.getLog();
Общая ошибка у многих ребят, если будет инициализация с конструктором по умолчанию будет нулл поинтер в этом месте.
Есть два пути:
1. Добавить обработку на нулл.
2. Исключить возникновение узкого места.

2019-12-26 09:25 UTC, KulyginaJulia commented on code/statistics-calculation/ViewModel/src/main/java/ru/unn/agile/StatisticsCalculation/viewmodel/ViewModel.java
> +        return logger.getLog();
done

2019-12-26 10:06 UTC, might52 approved these changes

2019-12-26 10:14 UTC, merged