Huffman log
UNN-ITMM-Software/agile-course-practice pull request #148
Opened 2019-12-25 21:09 UTC by NorthlaneKek

Created and tested log infrastructure for Huffman algorithm

2019-12-25 21:17 UTC, NorthlaneKek commented
@nik709 
@blackEagle

2019-12-25 21:19 UTC, NorthlaneKek commented
@nik709
@Vagik

2019-12-26 10:23 UTC, nik709 requested changes

2019-12-26 10:23 UTC, nik709 commented on code/huffman/Infrastructure/src/test/java/ru/unn/agile/huffman/infrastructure/TxtLoggerTests.java
> +
Нужно удалить пустую строку

2019-12-26 10:23 UTC, nik709 commented on code/huffman/View/src/main/java/ru/unn/agile/huffman/view/Main.java
> +        System.out.println(1);
???

2019-12-26 10:23 UTC, nik709 commented on code/huffman/ViewModel/src/test/java/ru/unn/agile/huffman/viewmodel/HuffmanViewModelTest.java
> +    public void setViewModel(final HuffmanViewModel vM) {
агрументу можно было бы придумать более информативное имя

2019-12-26 11:45 UTC, Vagik commented on code/huffman/ViewModel/src/test/java/ru/unn/agile/huffman/viewmodel/HuffmanViewModelTest.java
> +    @Test
Напиши тесты на проверку корректности логирования

2019-12-26 12:15 UTC, NorthlaneKek commented on code/huffman/View/src/main/java/ru/unn/agile/huffman/view/Main.java
> +        System.out.println(1);
)

2019-12-26 12:52 UTC, nik709 commented
👍

2019-12-26 12:59 UTC, Vagik commented
👍

2019-12-26 13:00 UTC, NorthlaneKek commented on code/huffman/ViewModel/src/test/java/ru/unn/agile/huffman/viewmodel/HuffmanViewModelTest.java
> +    @Test
> Напиши тесты на проверку корректности логирования

gotovo brat

2019-12-26 13:03 UTC, VitKonevskiy requested changes

2019-12-26 13:03 UTC, VitKonevskiy commented on code/huffman/Infrastructure/src/main/java/ru/unn/agile/huffman/infrastructure/TxtLogger.java
> +    private static final String DATE_FORMAT = "yyyy-MM-dd HH:mm:ss";
Лучше использовать yyyy-MM-dd HH:mm:ss.SSS

2019-12-26 13:03 UTC, VitKonevskiy commented on code/huffman/Infrastructure/src/main/java/ru/unn/agile/huffman/infrastructure/TxtLogger.java
> +            logWriter.write(now() + " >> " + message);
Перенеси разделитель в константы, пожалуйста

2019-12-26 14:07 UTC, merged