Симонян -- Лабораторная работа #0
UNN-ITMM-Software/agile-course-practice pull request #22
Opened 2019-11-05 12:54 UTC by Vagik

2019-11-05 13:01 UTC, Vagik commented
@nik709, @might52, please review

2019-11-05 13:48 UTC, nik709 requested changes

2019-11-05 13:48 UTC, nik709 commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/SimonyanVaginakTest.java
> +        assertEquals(sum, new ComplexNumber("7.6", "7.6"));
В `assertEquals` сначала идет ожидаемое значение, потом актуальное.
У тебя сделано наоборот.

2019-11-05 13:48 UTC, nik709 commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/SimonyanVaginakTest.java
> +        assertEquals(complexNumber1.getReal(), 3.1, compareDelta);
Тоже самое, что и для строки 35.

2019-11-05 13:48 UTC, nik709 commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/SimonyanVaginakTest.java
> +        assertEquals(complexNumber1.getImaginary(), 4.5, compareDelta);
Тоже самое, что и для строки 35.

2019-11-05 13:58 UTC, Vagik commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/SimonyanVaginakTest.java
> +        assertEquals(sum, new ComplexNumber("7.6", "7.6"));
Fixed

2019-11-05 13:58 UTC, Vagik commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/SimonyanVaginakTest.java
> +        assertEquals(complexNumber1.getReal(), 3.1, compareDelta);
Fixed

2019-11-05 13:58 UTC, Vagik commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/SimonyanVaginakTest.java
> +        assertEquals(complexNumber1.getImaginary(), 4.5, compareDelta);
Fixed

2019-11-05 14:03 UTC, nik709 approved these changes

2019-11-05 14:04 UTC, nik709 commented
:+1:

2019-11-06 19:34 UTC, VitKonevskiy commented
:+1:

2019-11-06 19:37 UTC, Vagik commented
@kirill-korniakov

2019-11-10 19:57 UTC, merged