Лапин -- Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice pull request #25
Opened 2019-11-05 19:23 UTC by Regmir

2019-11-05 19:27 UTC, Regmir commented
@karevboris @stepanshulpin посмотрите пожалуйста

2019-11-06 19:16 UTC, karevboris requested changes

2019-11-06 19:16 UTC, karevboris commented on code/quadratic-equasion/src/main/java/ru/unn/agile/QuadraticEquasion/model/QuadraticEquasion.java
> +//import ru.unn.agile.ComplexNumber.model.ComplexNumber;
Надо подчистить.

2019-11-06 19:16 UTC, karevboris commented on code/quadratic-equasion/src/test/java/ru/unn/agile/QuadraticEquasion/Model/QuadraticEquasionTests.java
> +    }
Зачем assert, если ждём эксепшен.

2019-11-06 19:16 UTC, karevboris commented on code/quadratic-equasion/src/test/java/ru/unn/agile/QuadraticEquasion/Model/QuadraticEquasionTests.java
> +    }
Наверное, коэффициент с не должен равняться нулю. И снова asseert + эксепшен.

2019-11-06 19:16 UTC, karevboris commented on code/quadratic-equasion/src/test/java/ru/unn/agile/QuadraticEquasion/Model/QuadraticEquasionTests.java
> +    }
Ещё можно добавить тест на этот же кейс, когда А=0, на проверку размера массива решений, убедиться что решение действительно только одно. Ну и размер массива solution достаточно 1, здесь опечатка.

2019-11-06 19:16 UTC, karevboris commented on code/quadratic-equasion/src/main/java/ru/unn/agile/QuadraticEquasion/model/Formatter.java
> +        i = (int) val % hundred;
Можно вынести в отдельный приватный метод с говорящим названием, чтобы не использовать комментарий.

2019-11-06 19:54 UTC, karevboris commented on code/quadratic-equasion/src/test/java/ru/unn/agile/QuadraticEquasion/Model/QuadraticEquasionTests.java
> +        assertEquals(solution[1].getImaginary(), actual[1].getImaginary(), delta);
Много assert, в идеале должен быть один. Можно сравнивать комплексные числа, а не отдельные части.

2019-11-07 10:14 UTC, Regmir commented on code/quadratic-equasion/src/test/java/ru/unn/agile/QuadraticEquasion/Model/QuadraticEquasionTests.java
> +        assertEquals(solution[1].getImaginary(), actual[1].getImaginary(), delta);
Результат нужно сравнивать с использованием дельты так как решения типа корня из двух в мнимой части комплексного числа сравнить на равенство не получится

2019-11-08 06:59 UTC, vgvoleg requested changes

2019-11-08 06:59 UTC, vgvoleg commented on code/quadratic-equasion/src/main/java/ru/unn/agile/QuadraticEquasion/model/Formatter.java
> +        String buffer = i.toString();
я не настаиваю, но возможно тут лучше будет использовать StringBuilder

2019-11-09 17:20 UTC, Regmir commented on code/quadratic-equasion/src/main/java/ru/unn/agile/QuadraticEquasion/model/Formatter.java
> +        String buffer = i.toString();
Изменил

2019-11-09 18:21 UTC, karevboris approved these changes
👍

2019-11-09 20:24 UTC, stepanshulpin commented on code/quadratic-equasion/src/main/java/ru/unn/agile/QuadraticEquasion/model/QuadraticEquasion.java
> +        if (part >= 0) {
Может вынести повторение в метод?

2019-11-09 20:29 UTC, stepanshulpin commented on code/quadratic-equasion/src/main/java/ru/unn/agile/QuadraticEquasion/model/Formatter.java
> +            .append(Math.abs(qe.getCCoeff()) != 0 ? c : "");
Может разбить эту логику на методы с понятным названием? Выглядит нечитаемо

2019-11-09 20:38 UTC, stepanshulpin commented on code/quadratic-equasion/src/main/java/ru/unn/agile/QuadraticEquasion/model/Formatter.java
> +    public static String formatPositiveDouble(final double value) {
По-моему этот код делает тоже самое _String.format ("%.2f", number);_

2019-11-10 08:44 UTC, Regmir commented on code/quadratic-equasion/src/main/java/ru/unn/agile/QuadraticEquasion/model/QuadraticEquasion.java
> +        if (part >= 0) {
Там нужно будет передать почти все параметры, все повторение просто переедет в метод, читать сложнее. Проще и понятней оставить в таком виде

2019-11-10 14:25 UTC, stepanshulpin commented
👍

2019-11-10 14:25 UTC, stepanshulpin approved these changes

2019-11-11 07:43 UTC, vgvoleg approved these changes

2019-11-11 07:55 UTC, vgvoleg requested changes

2019-11-11 07:55 UTC, vgvoleg commented on code/quadratic-equasion/src/test/java/ru/unn/agile/QuadraticEquasion/Model/QuadraticEquasionTests.java
> +        assertEquals(solution.length, 1);
сначала expected, потом actual

2019-11-11 08:03 UTC, vgvoleg approved these changes

2019-11-11 08:03 UTC, merged