Гречухин -- Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice pull request #37
Opened 2019-11-07 14:33 UTC by nik709

@might52 @VitKonevskiy

2019-11-07 15:12 UTC, vgvoleg requested changes

2019-11-07 15:12 UTC, vgvoleg commented on code/fractioncalculator/src/main/java/ru/unn/agile/fractioncalculator/Fraction.java
> +        return Math.abs(thisReducedFraction.numerator)
какое странное форматирование)) может для красоты вынести в отдельные переменные и return оформить в одну короткую строчку?

2019-11-07 15:12 UTC, vgvoleg commented on code/fractioncalculator/src/main/java/ru/unn/agile/fractioncalculator/FractionCalculator.java
> +package ru.unn.agile.fractioncalculator;
я конечно не настаиваю, но на мой взгляд все методы этого класса можно перенести в класс Fraction.
В таком случае будет очень удобно строить вычислительные цепочки а-ля f1.plus(f2).plus(f3).multiple(f4).reduce()

2019-11-07 15:13 UTC, VitKonevskiy commented on code/fractioncalculator/src/main/java/ru/unn/agile/fractioncalculator/FractionCalculator.java
> +        Objects.requireNonNull(second);
Could you move it to separate method to avoid duplication?

2019-11-07 15:13 UTC, VitKonevskiy commented on code/fractioncalculator/src/test/java/ru/unn/agile/fractioncalculator/FractionCalculatorTest.java
> +                FractionCalculator.sum(firstFraction, secondFraction)
Please, keep "AAA" principle: move FractionCalculator.sum from assert function to separate variable

2019-11-07 15:43 UTC, Vagik commented on code/fractioncalculator/src/main/java/ru/unn/agile/fractioncalculator/Fraction.java
> +        return numerator > 0 && denominator < 0 || numerator < 0 && denominator > 0;
It can be checked in another way: numerator * denominator < 0.
Seems to me more understandable

2019-11-07 15:51 UTC, nik709 commented on code/fractioncalculator/src/main/java/ru/unn/agile/fractioncalculator/Fraction.java
> +        return Math.abs(thisReducedFraction.numerator)
готово

2019-11-07 15:52 UTC, nik709 commented on code/fractioncalculator/src/main/java/ru/unn/agile/fractioncalculator/FractionCalculator.java
> +package ru.unn.agile.fractioncalculator;
в данном случае Fraction выступает в роли data class-а и не несет в себе логики калькулятора

2019-11-07 15:52 UTC, nik709 commented on code/fractioncalculator/src/main/java/ru/unn/agile/fractioncalculator/FractionCalculator.java
> +        Objects.requireNonNull(second);
готово

2019-11-07 15:52 UTC, nik709 commented on code/fractioncalculator/src/test/java/ru/unn/agile/fractioncalculator/FractionCalculatorTest.java
> +                FractionCalculator.sum(firstFraction, secondFraction)
готово

2019-11-07 15:52 UTC, nik709 commented on code/fractioncalculator/src/main/java/ru/unn/agile/fractioncalculator/Fraction.java
> +        return numerator > 0 && denominator < 0 || numerator < 0 && denominator > 0;
готово

2019-11-07 16:50 UTC, Vagik commented on code/fractioncalculator/src/main/java/ru/unn/agile/fractioncalculator/Fraction.java
> +        if (thisReducedFraction.isNegative() && !thatReducedFraction.isNegative()) {
Not all cases can be checked here. It is better to compare to boolean values

2019-11-07 16:53 UTC, nik709 commented on code/fractioncalculator/src/main/java/ru/unn/agile/fractioncalculator/Fraction.java
> +        if (thisReducedFraction.isNegative() && !thatReducedFraction.isNegative()) {
исправил

2019-11-07 17:11 UTC, VitKonevskiy commented
:+1:

2019-11-07 17:20 UTC, Vagik commented
👍

2019-11-07 17:50 UTC, vgvoleg commented
👍

2019-11-07 17:53 UTC, nik709 commented
@kirill-korniakov

2019-11-11 08:00 UTC, vgvoleg commented
@nik709 сделай rebase об новый мастер, теперь твоя секция в settings.gradle должна переехать в специально отведенное место

2019-11-11 19:52 UTC, vgvoleg approved these changes

2019-11-11 19:52 UTC, merged