Сизова -- Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice pull request #40
Opened 2019-11-07 22:45 UTC by ksenya-sizova

2019-11-07 22:48 UTC, ksenya-sizova commented
@Nikita-Mitrokhin, @YuferevKirill, please review my code. Thanks!

2019-11-09 21:00 UTC, Nikita-Mitrokhin commented on code/binary-search/src/test/java/ru/unn/agile/binarysearch/Model/BinarySearchTest.java
> +    public void canNullPointerException() {
Не очень удачное имя теста, лучше использовать что-то вроде canCallNullPointerException() или canExceptionForEmptyArray()

2019-11-09 21:00 UTC, Nikita-Mitrokhin commented on code/binary-search/src/test/java/ru/unn/agile/binarysearch/Model/BinarySearchTest.java
> +    }
Нет ни одного теста на метод isSorted(), можно добавить, например, что-то подобное:
       
        public void canCheckIsSortedForSortedArray() {
               int[] inputArray = {1, 2, 3};
               BinarySearch binarySearch = new BinarySearch(inputArray);
        
               assertTrue(binarySearch.isSorted());
        }

        public void canCheckIsSortedForUnsortedArray() {
               int[] inputArray = {3, 1, 2};
               BinarySearch binarySearch = new BinarySearch(inputArray);
        
               assertFalse(binarySearch.isSorted());
        }

2019-11-10 12:25 UTC, YuferevKirill commented on code/binary-search/src/test/java/ru/unn/agile/binarysearch/Model/BinarySearchTest.java
> +    public void canNullPointerException() {
Можно назвать ещё как canThrowExceptionName, цель то отследить сможет ли обработаться такой случай

2019-11-10 20:13 UTC, ksenya-sizova commented on code/binary-search/src/test/java/ru/unn/agile/binarysearch/Model/BinarySearchTest.java
> +    }
Данный методя является private методом. Я не смогу протестировать его указанным образом.

2019-11-10 21:05 UTC, VitKonevskiy commented on code/binary-search/src/test/java/ru/unn/agile/binarysearch/Model/BinarySearchTest.java
> +    public void canNullPointerException() {
Я бы предпочел cantCreateBinarySearchWithNullArray()

2019-11-10 21:05 UTC, VitKonevskiy commented on code/binary-search/src/test/java/ru/unn/agile/binarysearch/Model/BinarySearchTest.java
> +        assertEquals(binarySearch.search(element), expectedPosition);
Заголовок функции: 
`static public void assertEquals(long expected, long actual)`
Поменяй, пожалуйста, аргументы expectedPosition и binarySearch.search(element) местами.

2019-11-10 21:05 UTC, VitKonevskiy commented on settings.gradle
> +
Rebase pls

2019-11-11 12:17 UTC, Nikita-Mitrokhin commented on code/binary-search/src/test/java/ru/unn/agile/binarysearch/Model/BinarySearchTest.java
> +    }
Согласен, не заметил, моя ошибка.

2019-11-12 11:50 UTC, VitKonevskiy requested changes

2019-11-12 11:50 UTC, VitKonevskiy commented on code/binary-search/src/test/java/ru/unn/agile/binarysearch/Model/BinarySearchTest.java
> +package ru.unn.agile.binarysearch.Model;
use low-case for package naming, please

2019-11-12 18:59 UTC, ksenya-sizova commented on code/binary-search/src/test/java/ru/unn/agile/binarysearch/Model/BinarySearchTest.java
> +package ru.unn.agile.binarysearch.Model;
Fixed

2019-11-12 19:00 UTC, ksenya-sizova commented on code/binary-search/src/test/java/ru/unn/agile/binarysearch/Model/BinarySearchTest.java
> +        assertEquals(binarySearch.search(element), expectedPosition);
Fixed

2019-11-12 19:04 UTC, ksenya-sizova commented on code/binary-search/src/test/java/ru/unn/agile/binarysearch/Model/BinarySearchTest.java
> +    public void canNullPointerException() {
Test was renamed to `canNotCreateBinarySearchWithNullArray()`

2019-11-12 19:29 UTC, ksenya-sizova commented on settings.gradle
> +
Fixed

2019-11-12 19:32 UTC, ksenya-sizova commented
@YuferevKirill , @Nikita-Mitrokhin , please review again

2019-11-12 19:33 UTC, YuferevKirill commented
👍

2019-11-12 19:35 UTC, Nikita-Mitrokhin commented
:+1:

2019-11-12 19:36 UTC, VitKonevskiy approved these changes

2019-11-12 19:36 UTC, merged