Шульпин -- Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice pull request #41
Opened 2019-11-08 01:12 UTC by stepanshulpin

@Regmir, @karevboris, please review

2019-11-08 07:14 UTC, vgvoleg requested changes

2019-11-08 07:14 UTC, vgvoleg commented on code/mortgage-calculator/src/main/java/ru/unn/agile/mortgagecalculator/model/validation/Validator.java
> +public class Validator {
нет ни одной причины не сделать все методы этого класса статическими

2019-11-08 07:14 UTC, vgvoleg commented on code/mortgage-calculator/src/main/java/ru/unn/agile/mortgagecalculator/model/calculator/MortgageCalculator.java
> +        } else {
else не нужен

2019-11-08 07:14 UTC, vgvoleg commented on code/mortgage-calculator/src/main/java/ru/unn/agile/mortgagecalculator/model/calculator/MortgageCalculator.java
> +        } else {
else не нужен

2019-11-08 07:14 UTC, vgvoleg commented on code/mortgage-calculator/src/main/java/ru/unn/agile/mortgagecalculator/model/parameters/MortgageParameters.java
> +        validate(amount, percent, period);
внутри функции validate ты заново создаешь validator, со статическими методами класса Validator было бы попроще :)

2019-11-08 07:14 UTC, vgvoleg commented on code/mortgage-calculator/src/main/java/ru/unn/agile/mortgagecalculator/model/parameters/commission/FixedCommission.java
> +    public double calculate(final double amount) {
в интерфейсе наверное тоже можно пометить аргумент как final

2019-11-09 09:48 UTC, karevboris requested changes

2019-11-09 09:48 UTC, karevboris commented on code/mortgage-calculator/src/main/java/ru/unn/agile/mortgagecalculator/model/calculator/MortgageWithAnnuityPaymentsCalculator.java
> +            double paymentWithCommission =
Объявление локальных переменных лучше вынести перед циклом.

2019-11-09 09:48 UTC, karevboris commented on code/mortgage-calculator/src/main/java/ru/unn/agile/mortgagecalculator/model/calculator/MortgageWithDifferentialPaymentsCalculator.java
> +            double payment = basicPayment + percentPayment;
Также можно вынести объявление переменных за цикл.

2019-11-09 09:48 UTC, karevboris commented on code/mortgage-calculator/src/test/java/ru/unn/agile/mortgagecalculator/Model/MortgageCalculatorTest.java
> +    }
Наверное стоит переименовать данный тест и несколько тестов ниже в "canNot" так как ждём эксепшен, а не инициализацию.

2019-11-09 09:48 UTC, karevboris commented on code/mortgage-calculator/src/test/java/ru/unn/agile/mortgagecalculator/Model/MortgageCalculatorTest.java
> +    public void canCalculateWithInitialPaymentMoreThenAmount() {
Тоже стоит переименовать.

2019-11-09 09:53 UTC, karevboris commented on settings.gradle
> +project(":code/mortgage-calculator").name = "mortgage-calculator-Model"
Файл обновили, можно переставить в нужное место со своей фамилией.

2019-11-09 21:55 UTC, stepanshulpin commented on code/mortgage-calculator/src/main/java/ru/unn/agile/mortgagecalculator/model/parameters/commission/FixedCommission.java
> +    public double calculate(final double amount) {
Commission.java:5:22: Redundant 'final' modifier. [RedundantModifier]

2019-11-09 22:08 UTC, stepanshulpin commented on code/mortgage-calculator/src/main/java/ru/unn/agile/mortgagecalculator/model/parameters/MortgageParameters.java
> +        validate(amount, percent, period);
Исправил, спасибо

2019-11-09 22:09 UTC, stepanshulpin commented on code/mortgage-calculator/src/main/java/ru/unn/agile/mortgagecalculator/model/validation/Validator.java
> +public class Validator {
Исправил, спасибо

2019-11-09 22:09 UTC, stepanshulpin commented on code/mortgage-calculator/src/main/java/ru/unn/agile/mortgagecalculator/model/calculator/MortgageCalculator.java
> +        } else {
Исправил, спасибо

2019-11-09 22:09 UTC, stepanshulpin commented on code/mortgage-calculator/src/main/java/ru/unn/agile/mortgagecalculator/model/calculator/MortgageCalculator.java
> +        } else {
Исправил, спасибо

2019-11-09 22:09 UTC, stepanshulpin commented on code/mortgage-calculator/src/main/java/ru/unn/agile/mortgagecalculator/model/parameters/MortgageParameters.java
> +        validate(amount, percent, period);
Исправил, спасибо

2019-11-09 22:10 UTC, stepanshulpin commented on code/mortgage-calculator/src/main/java/ru/unn/agile/mortgagecalculator/model/calculator/MortgageWithAnnuityPaymentsCalculator.java
> +            double paymentWithCommission =
Исправил, спасибо

2019-11-09 22:10 UTC, stepanshulpin commented on code/mortgage-calculator/src/main/java/ru/unn/agile/mortgagecalculator/model/calculator/MortgageWithDifferentialPaymentsCalculator.java
> +            double payment = basicPayment + percentPayment;
Исправил, спасибо

2019-11-09 22:10 UTC, stepanshulpin commented on code/mortgage-calculator/src/test/java/ru/unn/agile/mortgagecalculator/Model/MortgageCalculatorTest.java
> +    }
Исправил, спасибо

2019-11-09 22:10 UTC, stepanshulpin commented on code/mortgage-calculator/src/test/java/ru/unn/agile/mortgagecalculator/Model/MortgageCalculatorTest.java
> +    public void canCalculateWithInitialPaymentMoreThenAmount() {
Исправил, спасибо

2019-11-09 22:10 UTC, stepanshulpin commented on settings.gradle
> +project(":code/mortgage-calculator").name = "mortgage-calculator-Model"
Исправил, спасибо

2019-11-10 09:54 UTC, karevboris approved these changes
👍

2019-11-10 14:27 UTC, vgvoleg commented
👍

2019-11-10 15:54 UTC, stepanshulpin commented
@kirill-korniakov

2019-11-11 20:23 UTC, vgvoleg approved these changes

2019-11-11 20:24 UTC, merged