Петров -- Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice pull request #45
Opened 2019-11-10 01:26 UTC by PetrovKP

2019-11-10 01:49 UTC, PetrovKP commented
@vgvoleg, @SmirnovEgorRu, @Lenferd please review this awesome code

2019-11-10 07:07 UTC, vgvoleg commented
Судя по истории коммитов, разработка не велась по циклу TDD

2019-11-10 10:05 UTC, PetrovKP commented
@vgvoleg нет четкого требования ни в TDD ни в условиях работы коммитить каждую пройденную итерацию. 

- kirill-korniakov, стоит ли при ревью кода оценивать кол-во коммитов в первой лабораторной работе и соблюдение цикла (TDD)?

- might52 соблюдение цикла конечно нужно требовать, весь смысл дабы в этом. Количество **коммитов волнует меньше**,  но в принципе можно попросить почистить историю, если глаз режет

2019-11-10 13:24 UTC, vgvoleg requested changes

2019-11-10 13:24 UTC, vgvoleg commented on code/interpolation_search/src/test/java/ru/unn/agile/interpolation_search/model/InterpolationSearchTest.java
> +            1
запиши тут и в аналогичных местах в одну строчку, у тебя не такие большие выражения чтобы плодить строчки кода

2019-11-10 13:24 UTC, vgvoleg commented on code/interpolation_search/src/main/java/ru/unn/agile/interpolation_search/model/InterpolationSearch.java
> +public class InterpolationSearch {
Не совсем понятно зачем создавать экземпляр класса. У класса нет никакого контекста - ты можешь либо сделать все его методы статическими, либо в конструктор передавать массив элементов, и уже многократно искать. Так как у тебя до поиска никакой предобработки массива нет(кроме проверки на отсортированность) то разумнее сделать все методы статическими. Если пойдешь по этому пути - не забудь сделать конструктор приватным.

2019-11-10 13:29 UTC, PetrovKP commented on code/interpolation_search/src/test/java/ru/unn/agile/interpolation_search/model/InterpolationSearchTest.java
> +            1
@vgvoleg Так вначале и делал, но  код стайл ругается. Требует чтобы скобка всегда открывалась в текущей строке, а закрывалась в другой.

2019-11-10 13:30 UTC, vgvoleg commented on code/interpolation_search/src/test/java/ru/unn/agile/interpolation_search/model/InterpolationSearchTest.java
> +            1
хорошо, закрывай замечание

2019-11-10 13:37 UTC, PetrovKP commented on code/interpolation_search/src/main/java/ru/unn/agile/interpolation_search/model/InterpolationSearch.java
> +public class InterpolationSearch {
@vgvoleg Валидный коммент. Тоже об этом думал, но не решился вначале :)

2019-11-10 13:38 UTC, PetrovKP commented on code/interpolation_search/src/main/java/ru/unn/agile/interpolation_search/model/InterpolationSearch.java
> +public class InterpolationSearch {
@vgvoleg Исправил

2019-11-10 13:55 UTC, vgvoleg commented
👍

2019-11-10 15:05 UTC, SmirnovEgorRu commented
👍

2019-11-10 15:31 UTC, PetrovKP commented
@kirill-korniakov

2019-11-11 08:12 UTC, vgvoleg commented on code/interpolation_search/src/main/java/ru/unn/agile/interpolation_search/model/InterpolationSearch.java
> +package ru.unn.agile.interpolation_search.model;
https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names
лучше поправить на interpolationsearch. с модулем для симметрии можно сделать тоже самое (не забудь обновить потом settings.gradle)

2019-11-12 13:19 UTC, vgvoleg approved these changes

2019-11-12 13:20 UTC, merged