Смирнов -- Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice pull request #48
Opened 2019-11-10 13:56 UTC by SmirnovEgorRu

2019-11-10 13:56 UTC, SmirnovEgorRu commented
@vgvoleg. @PetrovKP, please, review.

2019-11-10 14:56 UTC, PetrovKP commented
👍

2019-11-10 16:04 UTC, SmirnovEgorRu commented
@Lenferd, @PovelikinRostislav, could you, please, have a look?

2019-11-10 16:51 UTC, KalyanovDO commented
:+1:

2019-11-10 16:55 UTC, SmirnovEgorRu commented
@kirill-korniakov

2019-11-11 09:12 UTC, vgvoleg requested changes

2019-11-11 09:12 UTC, vgvoleg commented on code/priority-queue/src/test/java/ru/unn/agile/PriorityQueue/Model/PriorityQueueTest.java
> +        assertNull(null, val);
`assertNull(val)`  ? таких мест несколько

2019-11-11 09:12 UTC, vgvoleg commented on code/priority-queue/src/test/java/ru/unn/agile/PriorityQueue/Model/PriorityQueueTest.java
> +        assertNotEquals(null, pq);
`assertNotNull(pq)`

2019-11-11 09:12 UTC, vgvoleg commented on code/priority-queue/src/main/java/ru/unn/agile/PriorityQueue/model/PriorityQueue.java
> +package ru.unn.agile.PriorityQueue.model;
не используйте заглавные буквы в названиях пакетов
https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names

2019-11-11 09:12 UTC, vgvoleg commented on code/priority-queue/src/test/java/ru/unn/agile/PriorityQueue/Model/PriorityQueueTest.java
> +        assertEquals(1, v4);
один тест - один ассерт. Тут можно переделать и проверить тоже самое за один ассерт. В аналогичных местах тоже лучше переделать.

2019-11-11 09:12 UTC, vgvoleg commented on code/priority-queue/src/test/java/ru/unn/agile/PriorityQueue/Model/PriorityQueueTest.java
> +        assertEquals(1, val1, val2);
а что это за сигнатура? почему тут 3 аргумента?

2019-11-17 18:13 UTC, SmirnovEgorRu commented on code/priority-queue/src/test/java/ru/unn/agile/PriorityQueue/Model/PriorityQueueTest.java
> +        assertNull(null, val);
Applied

2019-11-17 18:13 UTC, SmirnovEgorRu commented on code/priority-queue/src/test/java/ru/unn/agile/PriorityQueue/Model/PriorityQueueTest.java
> +        assertNotEquals(null, pq);
Applied

2019-11-17 18:13 UTC, SmirnovEgorRu commented on code/priority-queue/src/test/java/ru/unn/agile/PriorityQueue/Model/PriorityQueueTest.java
> +        assertEquals(1, v4);
Applied

2019-11-17 18:13 UTC, SmirnovEgorRu commented on code/priority-queue/src/test/java/ru/unn/agile/PriorityQueue/Model/PriorityQueueTest.java
> +        assertEquals(1, val1, val2);
Applied

2019-11-17 18:13 UTC, SmirnovEgorRu commented on code/priority-queue/src/main/java/ru/unn/agile/PriorityQueue/model/PriorityQueue.java
> +package ru.unn.agile.PriorityQueue.model;
Applied

2019-11-17 18:14 UTC, SmirnovEgorRu commented
@vgvoleg, I have fixed your comments. Is it okay now?

2019-11-17 19:16 UTC, vgvoleg requested changes

2019-11-17 19:16 UTC, vgvoleg commented on code/priority-queue/src/test/java/ru/unn/agile/priority-queue/Model/PriorityQueueTest.java
> +        assertEquals(2, val1, val2);
Почему тут три аргумента?

2019-11-17 19:16 UTC, vgvoleg commented on code/priority-queue/src/test/java/ru/unn/agile/priority-queue/Model/PriorityQueueTest.java
> +        assertArrayEquals(arr, new float[]{4, 3, 2, 1}, 0);
Сначала expected, потом actual

2019-11-17 19:16 UTC, vgvoleg requested changes

2019-11-17 19:16 UTC, vgvoleg commented on code/priority-queue/src/main/java/ru/unn/agile/priority-queue/model/PriorityQueue.java
> +package ru.unn.agile.priority_queue.model;
Ну и пакет стоит назвать priorityqueue

2019-11-18 15:29 UTC, SmirnovEgorRu commented
@vgvoleg, fixed

2019-11-18 15:31 UTC, vgvoleg approved these changes

2019-11-18 15:32 UTC, merged