Кочетова -- Лабораторная работа #0
UNN-ITMM-Software/agile-course-practice pull request #52
Opened 2019-11-11 17:36 UTC by kochetovadasha

2019-11-11 17:41 UTC, kochetovadasha commented
@RomaDoronin

2019-11-11 17:51 UTC, RomaDoronin commented
:+1:

2019-11-11 19:49 UTC, vgvoleg commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/KochetovaDariaTest.java
> +        assertEquals(complexNumberFirst.add(complexNumberSecond), new ComplexNumber(5, 8));
`assertEquals(expected, actual)` - на первом месте то, что мы ожидаем

2019-11-11 19:50 UTC, vgvoleg requested changes

2019-11-11 19:50 UTC, vgvoleg commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/KochetovaDariaTest.java
> +        assertEquals(complexNumberFirst.add(complexNumberSecond), new ComplexNumber(5, 8));
`assertEquals(expected, actual)` - на первом месте то, что мы ожидаем

2019-11-12 10:33 UTC, kochetovadasha commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/KochetovaDariaTest.java
> +        assertEquals(complexNumberFirst.add(complexNumberSecond), new ComplexNumber(5, 8));
Done

2019-11-12 11:46 UTC, vgvoleg commented
👍

2019-11-12 11:46 UTC, vgvoleg approved these changes

2019-11-12 11:46 UTC, merged