Кулыгина -- Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice pull request #53
Opened 2019-11-13 10:10 UTC by KulyginaJulia

2019-11-13 10:14 UTC, KulyginaJulia commented
@Anna-Mironova, @SemyonBevzuk, please review

2019-11-13 16:15 UTC, Anna-Mironova commented on code/complex-number-calculation/src/main/java/ru/unn/agile/complexnumbercalculation/model/CalculatorComplexNumber.java
> +}
Добавь пожалуйста указание,что метод бросает исключение:
public ComplexNumber division(final ComplexNumber z1, final ComplexNumber z2) throws ArithmeticException {

2019-11-13 17:21 UTC, Anna-Mironova commented on code/complex-number-calculation/src/main/java/ru/unn/agile/complexnumbercalculation/model/CalculatorComplexNumber.java
> +    }
Пожалуйста, поправь названия методов в соответствии с рекомендациями по именованию: имена методов представляют собой глаголы или глагольные сочетания, из которых очевидно из назначение.

2019-11-15 15:50 UTC, Anna-Mironova commented
👍

2019-11-15 19:22 UTC, SemyonBevzuk commented on code/complex-number-calculation/src/main/java/ru/unn/agile/complexnumbercalculation/model/ComplexNumber.java
> +    private double radius;
Стоит переименовать поле radius, у комплексных чисел есть модуль.

2019-11-15 19:22 UTC, SemyonBevzuk commented on code/complex-number-calculation/src/main/java/ru/unn/agile/complexnumbercalculation/model/ComplexNumber.java
> +    private double angle;
И аргумент.

2019-11-15 19:22 UTC, SemyonBevzuk commented on code/complex-number-calculation/src/main/java/ru/unn/agile/complexnumbercalculation/model/ComplexNumber.java
> +
Хотелось бы инициализировать комплексное число не только через алгебраическую форму, но и через тригонометрическую.

2019-11-15 19:22 UTC, SemyonBevzuk commented on code/complex-number-calculation/src/main/java/ru/unn/agile/complexnumbercalculation/model/ComplexNumber.java
> +        if ((re == 0) && (im == 0)) {
Тут ты работаешь с вещественными числами и проверяешь их равенство нулю. Но в классе есть параметр delta, который устанавливает какую окрестность нуля мы считаем нулем. Может быть стоит написать |re| < delta?

2019-11-15 19:22 UTC, SemyonBevzuk commented on code/complex-number-calculation/src/main/java/ru/unn/agile/complexnumbercalculation/model/ComplexNumber.java
> +    private final double delta = 0.001;
Думаю будет полезно дать доступ к параметру точности твоего комплексного числа. Тогда снаружи можно будет обратиться к getAccuracy и узнать какую именно точность гарантирует твой класс при вычислениях.

2019-11-15 19:22 UTC, SemyonBevzuk commented on code/complex-number-calculation/src/main/java/ru/unn/agile/complexnumbercalculation/model/CalculatorComplexNumber.java
> +        z.convertToTrigonomForm();
Данное решение не очень хорошее. Можно же вычислить аргумент и модуль при инициализации комплексного числа. Или вычислять их при обращении через алгебраическую форму.

2019-11-15 19:22 UTC, SemyonBevzuk commented on code/complex-number-calculation/src/main/java/ru/unn/agile/complexnumbercalculation/model/CalculatorComplexNumber.java
> +public class CalculatorComplexNumber {
Ещё для комплексных чисел можно считать сопряженное число. Стоит добавить такую возможность в калькулятор.

2019-11-15 19:22 UTC, SemyonBevzuk commented on code/complex-number-calculation/src/main/java/ru/unn/agile/complexnumbercalculation/model/ComplexNumber.java
> +    }
Зачем кому-то снаружи устанавливать значение приватных полей?
Безопаснее сделать класс ComplexNumber не мутабельным.
Тогда все поля будут заданы при инициализации и вся работа с изменением полей будет только в операциях.

2019-11-15 19:22 UTC, SemyonBevzuk commented on code/complex-number-calculation/src/main/java/ru/unn/agile/complexnumbercalculation/model/ComplexNumber.java
> +    }
Лучше все таки переименовать поля и геттеры в стандартных терминах.

2019-11-15 19:22 UTC, SemyonBevzuk commented on code/complex-number-calculation/src/main/java/ru/unn/agile/complexnumbercalculation/model/ComplexNumber.java
> +        angle = 0.0;
Почему тригонометрическая форма userRe+i*userIm всегда нулевая?
Если я создам ComplexNumber(1, 1) и сразу после вызову у него getRadius или getAngle, то получу ноль, хотя это не так.

Здесь и в других конструкторах можно заполнить эти поля просто вычислив их при инициализации.
Или не хранить поля модуля и аргумента, а вычислять их при вызове.

2019-11-15 19:22 UTC, SemyonBevzuk commented on code/complex-number-calculation/src/test/java/ru/unn/agile/complexnumbercalculation/model/ComplexNumberTest.java
> +
Хорошо бы добавить отдельные тесты на getRadius и getAngle.
Вот пример тестов, который сейчас упадут: 
```
     @Test
     public void canGetRadiusNot0() {
         ComplexNumber a = new ComplexNumber(1, 1);

         assertEquals(Math.sqrt(2), a.getRadius(), 0.001);
     }


     @Test
     public void canGetAngleNot0() {
         ComplexNumber a = new ComplexNumber(1, 1);

         assertEquals(Math.PI / 4, a.getAngle(), 0.001);
     }
```

2019-11-15 19:22 UTC, SemyonBevzuk commented on code/complex-number-calculation/src/test/java/ru/unn/agile/complexnumbercalculation/model/ComplexNumberTest.java
> +        assertEquals(2, a.getRadius(), 0.001);
0.001 часто используется в тестах, стоит выделить в константу или дёргать из класса. Вдруг ты изменишь точность работы и тебе придётся сделать множество изменений во всех тестах.

2019-11-15 19:22 UTC, SemyonBevzuk commented on code/complex-number-calculation/src/test/java/ru/unn/agile/complexnumbercalculation/model/ComplexNumberTest.java
> +
Нет тестов на getComplexNumberFromTrigonomForm(), а она public. Хотя от данной функции можно избавиться, если иначе заполнять поля класса ComplexNumber.

2019-11-15 19:57 UTC, vgvoleg requested changes

2019-11-15 19:57 UTC, vgvoleg commented on code/complex-number-calculation/src/main/java/ru/unn/agile/complexnumbercalculation/model/CalculatorComplexNumber.java
> +public class CalculatorComplexNumber {
Пожалуйста, переименуй свой класс в ComplexNumberCalculator, текущее название звучит криво.
Данный класс не имеет никакого контекста, соответственно нет ни одной причины не сделать все методы статическими, как например у класса Math

2019-11-17 13:27 UTC, SemyonBevzuk commented on code/complex-number-calculator/src/main/java/ru/unn/agile/complexnumbercalculator/model/ComplexNumber.java
> +    }
Можно добавить возможность создавать ComplexNumber из двух форм. Это позволит упростить операции extractRoot и pow. Помимо этого, можно будет избавиться от текущей не очень логичной последовательности действий при создании комплексного числа через модуль и  аргумент. Сейчас это выглядит так:
```
ComplexNumber a = new ComplexNumber(0,0);
a. setTrigonometricForm(module, argument);
```
Это не очень удобно.

Эту ситуацию можно решить двумя путями:

1. Выделить отдельный классы для таких сущностей как module и argument. Они заслуживают быть отдельными классами, так как обладают рядом свойств (module >= 0, argument это угол от 0 до 2*PI), которые double не гарантирует. Тогда у нас будет два конструктора с разным набором параметров для каждой формы.
2. Что-то вроде паттерна шаблонный метод. Сделать текущий конструктор алгебраической формы приватным. Добавить два статических метода для создания каждой формы createAlgebraicForm и createTrigonometricForm. Они могут принимать те же double и внутри инициализировать все поля. Тогда создание объекта будет выглядеть как-то так: 
```
ComplexNumber a = ComplexNumber.createAlgebraicForm(re, im)
ComplexNumber b = ComplexNumber.createTrigonometricForm(module, argument)
```

2019-11-17 13:27 UTC, SemyonBevzuk commented on code/complex-number-calculator/src/main/java/ru/unn/agile/complexnumbercalculator/model/ComplexNumber.java
> +    }
userPhase лучше заменить на userArgument

2019-11-17 13:27 UTC, SemyonBevzuk commented on code/complex-number-calculator/src/main/java/ru/unn/agile/complexnumbercalculator/model/ComplexNumber.java
> +    }
Да и при правильном создании объектов эта функция не нужна.

2019-11-17 13:27 UTC, SemyonBevzuk commented on code/complex-number-calculator/src/main/java/ru/unn/agile/complexnumbercalculator/model/ComplexNumber.java
> +    }
При новых конструкторах может быть private

2019-11-17 13:27 UTC, SemyonBevzuk commented on code/complex-number-calculator/src/main/java/ru/unn/agile/complexnumbercalculator/model/ComplexNumberCalculator.java
> +    }
С правильными конструкторами это можно упростить до следующего вида:
```
ComplexNumber zResult = new ComplexNumber(tempRadius, tempAngle);
```
или
```
ComplexNumber zResult = ComplexNumber.createsetTrigonometricForm(tempRadius, tempAngle);
```

2019-11-17 13:27 UTC, SemyonBevzuk commented on code/complex-number-calculator/src/main/java/ru/unn/agile/complexnumbercalculator/model/ComplexNumberCalculator.java
> +        double tempAngle = degree * z.getArgument();
Снова углы и радиус вместо аргумента и модуля  :)

2019-11-17 13:27 UTC, SemyonBevzuk commented on code/complex-number-calculator/src/main/java/ru/unn/agile/complexnumbercalculator/model/ComplexNumberCalculator.java
> +            result[k] = zTmp;
Аналогично, конструкторы упростят создание нового объекта.

2019-11-17 14:46 UTC, SemyonBevzuk commented
👍

2019-11-17 16:05 UTC, vgvoleg requested changes

2019-11-17 16:05 UTC, vgvoleg commented on code/complex-number-calculator/src/main/java/ru/unn/agile/complexnumbercalculator/model/ComplexNumberCalculator.java
> +     //   ComplexNumber zResult = ComplexNumber.createTrigonometricForm(tempRadius, tempAngle);
Убери пожалуйста ненужный код

2019-11-17 16:05 UTC, vgvoleg commented on code/complex-number-calculator/src/test/java/ru/unn/agile/complexnumbercalculator/model/ComplexNumberCalculatorTest.java
> +    public void operationAdditionalCalculatorComplexNumber() {
Названия тестов должны озвучивать **утверждения**. Тесты в таком случае читаются следующим образом: для ComplexNumberCalculator (имя тестируемого класса) справедливо/не справедливо следующее утверждение (название теста)
То есть если твой тест проверяет сложение, метод должен называться «может складывать два числа» или «сложение работает корректно» или что угодно, что является утверждением

2019-11-17 16:05 UTC, vgvoleg commented on code/complex-number-calculator/src/test/java/ru/unn/agile/complexnumbercalculator/model/ComplexNumberCalculatorTest.java
> +    public void operationMultiplicationCalculatorComplexNumberWithOneNull() {
Более того, нет смысла в каждом тесте упоминать название тестируемого класса - оно отражено в названии набора тестов (классе)

2019-11-17 16:30 UTC, KulyginaJulia commented
Done

2019-11-17 19:00 UTC, vgvoleg approved these changes

2019-11-17 19:00 UTC, merged