Купцова -- Лабораторная работа #0
UNN-ITMM-Software/agile-course-practice pull request #59
Opened 2019-11-13 21:56 UTC by alesya-kuptsova

2019-11-14 19:29 UTC, YuferevKirill requested changes

2019-11-14 19:29 UTC, YuferevKirill commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/KuptsovaAlesyaTest.java
> +        assertEquals(new ComplexNumber(14, -5), num);
You need to take _new ComplexNumber(14, -5)_ to somethink like "expectedValue" variable,
and _num_ to "actualValue" variable everywhere

2019-11-14 19:29 UTC, YuferevKirill commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/KuptsovaAlesyaTest.java
> +        String numstr = valueOf(num);
please use the lowerCamelCase everywhere

2019-11-14 19:29 UTC, YuferevKirill commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/KuptsovaAlesyaTest.java
> +    public void canGetRealFromComplexNumberWithARealPart() {
change name please, what's the 'A' in ...WithARealPart ?

2019-11-14 19:29 UTC, YuferevKirill commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/KuptsovaAlesyaTest.java
> +    @Test
add blank line after each test

2019-11-14 19:29 UTC, YuferevKirill commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/KuptsovaAlesyaTest.java
> +        String numstr = valueOf(num);
it is not necessary to convert numbers into strings

2019-11-14 19:29 UTC, YuferevKirill commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/KuptsovaAlesyaTest.java
> +    public void canMultiplyNumbersWithNegativePartS() {
remove 'S' at the end of test name and write 's'. Please

2019-11-14 19:29 UTC, YuferevKirill commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/KuptsovaAlesyaTest.java
> +}
add blank line at the end of file

2019-11-14 19:29 UTC, YuferevKirill commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/KuptsovaAlesyaTest.java
> +    @Rule
i think you need to add blank line before _@Rule_

2019-11-14 19:29 UTC, YuferevKirill commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/KuptsovaAlesyaTest.java
> +        thrown.expect(IllegalArgumentException.class);
can you rewrite test to somethink like that:
    @Test(expected = IllegalArgumentException.class)
    public void canNotCreateComplexNumberWithUncorrectValues() {
          your_test
    }

2019-11-14 20:49 UTC, alesya-kuptsova commented
@mkildishev

2019-11-16 23:06 UTC, alesya-kuptsova commented
@YuferevKirill , fixed! Thanks for your comments!)
@mkildishev

2019-11-17 14:51 UTC, mkildishev commented
👍

2019-11-17 15:40 UTC, vgvoleg commented
👍

2019-11-17 15:40 UTC, merged