Алексеев -- Лабораторная работа #0
UNN-ITMM-Software/agile-course-practice pull request #62
Opened 2019-11-15 09:46 UTC by Folifolo

2019-11-15 09:55 UTC, Folifolo commented
@Edvard-Hagerup-Grieg @Nikita-Mitrokhin

2019-11-15 09:59 UTC, Edvard-Hagerup-Grieg commented
:+1:

2019-11-15 10:22 UTC, Nikita-Mitrokhin commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/AlekseevSergeiTest.java
> +        assertEquals(1.1, z.getReal(), delta);
You use magic numbers in assert, please, change it with something like that:

    public void canGetRealPart() {
        //Arrange
        ComplexNumber z = new ComplexNumber(1.1, 2.3);

        //Act
        var realPartComplex = z.getReal(); 
        var expectedRealPart = 1.1;

        //Assert
        assertEquals(expectedRealPart, realPartComplex, delta);

2019-11-15 10:22 UTC, Nikita-Mitrokhin commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/AlekseevSergeiTest.java
> +        assertEquals(2.3, z.getImaginary(), delta);
similar here(magic numbers)

2019-11-15 10:22 UTC, Nikita-Mitrokhin commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/AlekseevSergeiTest.java
> +        assertEquals(new ComplexNumber(3, 4), z);
class instance creation is best remove from assert:

    public void canAddNumbers() {
        //Arrange
        ComplexNumber z1 = new ComplexNumber(1, 1);
        ComplexNumber z2 = new ComplexNumber(2, 3);

        //Act
        ComplexNumber sumComplex = z1.add(z2);
        ComplexNumber expectedComplexNumber = new ComplexNumber(3, 4);

        //Assert
        assertEquals(expectedComplexNumber, sumComplex);

2019-11-15 10:22 UTC, Nikita-Mitrokhin commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/AlekseevSergeiTest.java
> +        assertEquals(new ComplexNumber(-1, 5), z);
similar here(class instance creation remove)

2019-11-15 10:22 UTC, Nikita-Mitrokhin commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/AlekseevSergeiTest.java
> +        assertEquals("1.1 + 2.35i", z.toString());
similar here(magic numbers):

    public void canFormatNumbers() {
        // Arrange
        ComplexNumber z = new ComplexNumber(1.1, 2.35);

        // Act
        String strComplex = z.toString();
        var expectedString = "1.1 + 2.35i";

        // Assert
        assertEquals(expectedString, strComplex);

2019-11-15 10:22 UTC, Nikita-Mitrokhin commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/AlekseevSergeiTest.java
> +        assertTrue(sum.equals(z));
it’s better not to equals in assert:

    public void areAddingZeroDoesntChangeNumber() {
        //Arrange  
        ComplexNumber z = new ComplexNumber(1.1, 2.3);
        ComplexNumber zero = new ComplexNumber(0.0, 0.0);

        //Act
        ComplexNumber sum = z.add(zero);

        //Assert
        assertEquals(sum, z);

2019-11-15 10:22 UTC, Nikita-Mitrokhin commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/AlekseevSergeiTest.java
> +        assertTrue(mult.equals(zero));
similar here(not to equals in assert):

    public void areMultiplicationByZeroChangeNumber() {
        //Arrange
        ComplexNumber z = new ComplexNumber(1.1, 2.3);
        ComplexNumber zero = new ComplexNumber(0.0, 0.0);

        //Act
        ComplexNumber mult = z.multiply(zero);

        //Assert
        assertEquals(mult, zero);

2019-11-15 19:50 UTC, vgvoleg requested changes

2019-11-15 19:50 UTC, vgvoleg commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/AlekseevSergeiTest.java
> +    private final double delta = 0.00000001;
Поля класса как правило объявляются над методами. Ну и чтобы не писать кучу нолей, а другим потом их не считать, можно использовать запись вида `1e-8` (если ты уверен что тебе необходима такая точность)

2019-11-15 19:50 UTC, vgvoleg commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/AlekseevSergeiTest.java
> +    public void areAddingZeroDoesntChangeNumber() {
В названиях тестов принято озвучивать **утверждения**, а не вопросы. В нескольких местах надо поправить

2019-11-16 14:43 UTC, Nikita-Mitrokhin commented
:+1:

2019-11-16 18:51 UTC, vgvoleg approved these changes

2019-11-16 18:51 UTC, vgvoleg commented
👍

2019-11-16 18:51 UTC, merged