Конева -- Лабораторная работа #0
UNN-ITMM-Software/agile-course-practice pull request #64
Opened 2019-11-15 13:20 UTC by Edvard-Hagerup-Grieg

2019-11-15 13:27 UTC, Edvard-Hagerup-Grieg commented
@Folifolo

2019-11-15 13:30 UTC, Folifolo commented
:+1:

2019-11-15 13:59 UTC, Edvard-Hagerup-Grieg commented
@PetrovKP

2019-11-15 15:05 UTC, PetrovKP reviewed
👍

2019-11-15 15:05 UTC, PetrovKP commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/KonevaAleksandraTest.java
> +        ComplexNumber z1 = new ComplexNumber(1, 2);
Если делаешь по патерну AAA, лучше разделять, хотя бы переносом блоки. Читабельнее становится

2019-11-15 19:40 UTC, vgvoleg requested changes

2019-11-15 19:40 UTC, vgvoleg commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/KonevaAleksandraTest.java
> +    public void isAddCommutative() {
В названиях тестов принято озвучивать **утверждения**, а не вопросы. Лучше переименовать на `addIsCommutative` ну или на что-то около

2019-11-16 18:49 UTC, vgvoleg approved these changes

2019-11-17 15:38 UTC, merged