Красильников -- Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice pull request #66
Opened 2019-11-15 22:34 UTC by NorthlaneKek

2019-11-16 11:43 UTC, NorthlaneKek commented
@vgvoleg 
@kochetovadasha 
@kiselik

2019-11-16 12:24 UTC, VitKonevskiy requested changes

2019-11-16 12:24 UTC, VitKonevskiy commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/KrasilnikovMikhailComplexNumberTest.java
> +package ru.unn.agile.ComplexNumber.Model;
@NorthlaneKek , У меня есть подозрение, что это файл с нулевой лабы. Проверь, пожалуйста

2019-11-16 12:46 UTC, NorthlaneKek commented on code/korniakov-kirill-lab1/src/test/java/ru/unn/agile/ComplexNumber/Model/KrasilnikovMikhailComplexNumberTest.java
> +package ru.unn.agile.ComplexNumber.Model;
да, с нулевой лабы

2019-11-17 15:23 UTC, nik709 requested changes

2019-11-17 15:23 UTC, nik709 commented on code/salary-calculator/src/main/java/ru/unn/agile/salarycalculator/model/CalendarService.java
> +        checkingPeriod.setVacationDuration(this.getVacationDuration());
Можно использовать чейнинг вызовов, чтобы исключить лишнее указание переменной каждой раз

2019-11-17 15:23 UTC, nik709 commented on code/salary-calculator/src/main/java/ru/unn/agile/salarycalculator/model/CalendarService.java
> +        System.out.println(checkingPeriod);
Уверен, что тут нужен вывод в консоль?

2019-11-17 15:23 UTC, nik709 commented on code/salary-calculator/src/main/java/ru/unn/agile/salarycalculator/model/SalaryCalculator.java
> +        int workingDaysPerCountedMonth = calendarService.countWorkingDaysInMonth();
Можно избежать использование лишней переменной с помощью чейнинга:
`new CalendarService().setMonth(getCountingMonth()).countWorkingDaysInMonth()`

2019-11-17 16:24 UTC, nik709 commented
👍

2019-11-17 16:38 UTC, kochetovadasha commented
👍

2019-11-17 20:27 UTC, merged