Конева -- Лабораторная работа #1
UNN-ITMM-Software/agile-course-practice pull request #71
Opened 2019-11-17 07:24 UTC by Edvard-Hagerup-Grieg

2019-11-17 07:28 UTC, Edvard-Hagerup-Grieg commented
@Folifolo

2019-11-17 07:29 UTC, Edvard-Hagerup-Grieg commented
@PetrovKP

2019-11-17 13:47 UTC, Folifolo commented on code/numbers-in-words/src/main/java/ru/unn/agile/numbersinwords/model/NumberToWordConverter.java
> +
Package names are all lowercase, with consecutive words simply concatenated together (no underscores).

2019-11-17 13:47 UTC, Folifolo commented on code/numbers-in-words/src/main/java/ru/unn/agile/numbersinwords/model/NumberToWordConverter.java
> +        return "";
Метод не используется

2019-11-17 13:47 UTC, Folifolo commented on code/numbers-in-words/src/test/java/ru/unn/agile/NumbersInWords/Model/NumberToWordConverterTest.java
> +}
Нет тестов/логики для отрицательных значений и нуля

2019-11-17 14:43 UTC, PetrovKP commented on code/numbers-in-words/src/main/java/ru/unn/agile/numbersinwords/model/NumberToWordConverter.java
> +        final String[] teens = {"ten", "eleven", "twelve", "thirteen", "fourteen",
Не вижу чтобы было протестировано со словом `thirteen`, `sixteen`,  `seventeen`, `eighteen`,, `nineteen`. Все таки при TDD ты не должна продумывать кейсы заранее. Только по результату тестирования.

2019-11-17 14:43 UTC, PetrovKP commented on code/numbers-in-words/src/main/java/ru/unn/agile/numbersinwords/model/NumberToWordConverter.java
> +    private final int ten = 10;
думаю логично сделать их статическими, и скорее всего правила именований констант подразумевает другой стиль.

2019-11-17 18:14 UTC, PetrovKP commented
👍

2019-11-17 18:38 UTC, Folifolo commented
:+1:

2019-11-17 18:58 UTC, vgvoleg requested changes

2019-11-17 18:58 UTC, vgvoleg commented on code/numbers-in-words/src/main/java/ru/unn/agile/numbersinwords/model/NumberToWordConverter.java
> +    public NumberToWordConverter() { }
Конструктор надо сделать приватным, а все методы - статическими. У класса нет контекста, соответственно, нет причин его инстанциировать

2019-11-17 18:58 UTC, vgvoleg commented on code/numbers-in-words/src/main/java/ru/unn/agile/numbersinwords/model/NumberToWordConverter.java
> +        if ((numberForAnalysis >= TEN) && (numberForAnalysis < twenty)) {
Эта строчка смотрится очень странно, для чего-то ты создаешь переменную на уровне класса, для чего-то на уровне метода. Если есть нужда хранить именованные константы, можешь воспользоваться енумами

2019-11-17 18:58 UTC, vgvoleg commented on code/numbers-in-words/src/test/java/ru/unn/agile/NumbersInWords/Model/NumberToWordConverterTest.java
> +        assertEquals("five hundred", word);
А что не `a half thousand`? :) править не обязательно, но было бы интересно))

2019-11-18 08:59 UTC, vgvoleg approved these changes

2019-11-18 08:59 UTC, merged