Киселева -- Лабораторная работа 1
UNN-ITMM-Software/agile-course-practice pull request #73
Opened 2019-11-18 13:25 UTC by kiselik

2019-11-18 13:26 UTC, kiselik commented
@kochetovadasha 
@NorthlaneKek 
@vgvoleg 
@VitKonevskiy

2019-11-22 09:01 UTC, kochetovadasha commented
👍

2019-11-30 15:37 UTC, vgvoleg requested changes

2019-11-30 15:37 UTC, vgvoleg commented on code/huffman/src/main/java/ru/unn/agile/huffman/model/Huffman.java
> +    public Huffman(final String str) {
Ты уверена, что этот класс вообще надо инстанциировать вместо создания статического метода encode?

2019-12-15 21:13 UTC, vgvoleg requested changes

2019-12-15 21:13 UTC, vgvoleg commented on code/huffman/src/main/java/ru/unn/agile/huffman/model/Huffman.java
> +        return Huffman.encodedString;
Зачем тебе хранить encodedString? Зачем на него геттер? Посчитала в методе - вернула. В этом и суть статических методов и в частности таких вот классов с исключительно статическими методами - у классов нет никакого контекста и внутреннего состояния.

2019-12-15 21:13 UTC, vgvoleg commented on code/huffman/src/main/java/ru/unn/agile/huffman/model/Huffman.java
> +        return Huffman.decodedString;
Тут тоже самое

2019-12-15 21:13 UTC, vgvoleg commented on code/huffman/src/main/java/ru/unn/agile/huffman/model/Huffman.java
> +    @Override
Ни toString, ни hashCode в классе который нельзя инстанциировать переопределять не надо

2019-12-15 21:13 UTC, vgvoleg commented on code/huffman/src/main/java/ru/unn/agile/huffman/model/Huffman.java
> +public class Huffman {
Добавь на этот класс приватный конструктор, чтобы никто не мог создать экземпляр класса, а мог только использовать encode и decode методы.

2019-12-15 21:13 UTC, vgvoleg commented on code/huffman/src/main/java/ru/unn/agile/huffman/model/Huffman.java
> +    public static void encodString(final String str) {
encod*E*

2019-12-15 21:13 UTC, vgvoleg commented on code/huffman/src/main/java/ru/unn/agile/huffman/model/Huffman.java
> +    public boolean equals(final Object object) {
Ну и этот метод переопределять не надо

2019-12-15 21:13 UTC, vgvoleg commented on code/huffman/src/test/java/ru/unn/agile/huffman/model/HuffmanTest.java
> +    public void canCreateHuffmanWithEmptyString() {
Этот тест не нужен. Твой класс не должен даже думать о том какая там исходная строка была. Он умеет кодировать - пусть этим и занимается.

2019-12-15 21:13 UTC, vgvoleg commented on code/huffman/src/test/java/ru/unn/agile/huffman/model/HuffmanTest.java
> +    public void decodedStringIsCorrectWith1AlphabeticSymbolInput() {
Этот и прочие подобные тесты на decodedString не нужны. Ты по факту в разных видах тестируешь пару сеттер-геттер.

2019-12-16 11:04 UTC, vgvoleg requested changes

2019-12-16 11:04 UTC, vgvoleg commented on code/huffman/src/main/java/ru/unn/agile/huffman/model/Huffman.java
> +    private Huffman() {
Это можно сделать при объявлении) лучше оставить конструктор пустым

2019-12-16 11:04 UTC, vgvoleg commented on code/huffman/src/test/java/ru/unn/agile/huffman/model/HuffmanTest.java
> +        Huffman.encodeString("");
Тут есть лишняя строчка

2019-12-17 10:28 UTC, kiselik commented on code/huffman/src/main/java/ru/unn/agile/huffman/model/Huffman.java
> +    private Huffman() {
fixed

2019-12-17 10:29 UTC, kiselik commented on code/huffman/src/test/java/ru/unn/agile/huffman/model/HuffmanTest.java
> +        Huffman.encodeString("");
fixed

2019-12-17 12:01 UTC, vgvoleg approved these changes

2019-12-17 12:01 UTC, merged