Шульпин -- Лабораторная работа #2
UNN-ITMM-Software/agile-course-practice pull request #76
Opened 2019-11-24 01:10 UTC by stepanshulpin

2019-11-24 01:14 UTC, stepanshulpin commented
@Regmir, @karevboris, please review

2019-11-26 14:01 UTC, karevboris requested changes

2019-11-26 14:01 UTC, karevboris commented on code/length-converter/View/src/main/java/ru/unn/agile/converter/view/LengthConverter.java
> +public class LengthConverter {
Лучше поменять название на LengthConverterView чтобы не путать с моделью.

2019-11-26 14:01 UTC, karevboris commented on code/length-converter/ViewModel/src/main/java/ru/unn/agile/converter/viewmodel/ViewModel.java
> +public class ViewModel {
Надо сменить на LengthConverterViewModel.

2019-11-26 14:01 UTC, karevboris commented on settings.gradle
> +project(":code/length-converter/ViewModel").name = "length-converter-ViewModel"
Наверное лучше перенести в то место где и модель, чтобы все части проекта конвертера были в одном месте. Конфликта не будет, т к я делал по тому же принципу.

2019-12-01 08:32 UTC, Regmir commented on code/length-converter/ViewModel/src/main/java/ru/unn/agile/converter/viewmodel/ViewModel.java
> +    private void onInput(final String newValue) {
Если оставить проверку в таком виде то при вводе 2х неправильных полей подряд и исправлении одного их них система посчитает что ввод корректен

2019-12-01 08:32 UTC, Regmir commented on code/length-converter/ViewModel/src/main/java/ru/unn/agile/converter/viewmodel/ViewModel.java
> +    private boolean isNumeric(final String str) {
Почему не сделать проверку через Double.parseDouble() в try/catch блоке?

2019-12-01 08:32 UTC, Regmir commented on code/length-converter/ViewModel/src/main/java/ru/unn/agile/converter/viewmodel/ViewModel.java
> +        error.set(isNumeric || newValue.isEmpty() ? "" : "invalid");
А отрицательное значение считается валидным?

2019-12-01 08:32 UTC, Regmir commented on settings.gradle
> +project(":code/length-converter/ViewModel").name = "length-converter-ViewModel"
Теперь вроде нужно перенести все в одно место с заголовком LenghtConverter без фамилии

2019-12-04 17:53 UTC, stepanshulpin commented on code/length-converter/ViewModel/src/main/java/ru/unn/agile/converter/viewmodel/ViewModel.java
> +    private void onInput(final String newValue) {
Только одно поле дл ввода

2019-12-04 17:55 UTC, stepanshulpin commented on code/length-converter/ViewModel/src/main/java/ru/unn/agile/converter/viewmodel/ViewModel.java
> +    private boolean isNumeric(final String str) {
Я так сделал, потому что пустое значение не является не валидным, но для parseDouble оно некорректно

2019-12-04 17:55 UTC, stepanshulpin commented on code/length-converter/ViewModel/src/main/java/ru/unn/agile/converter/viewmodel/ViewModel.java
> +        error.set(isNumeric || newValue.isEmpty() ? "" : "invalid");
да

2019-12-04 18:29 UTC, Regmir commented on code/length-converter/ViewModel/src/test/java/ru/unn/agile/converter/viewmodel/LengthConverterLengthConverterViewModelTests.java
> +public class LengthConverterLengthConverterViewModelTests {
LengthConverter дважды в названии

2019-12-04 19:10 UTC, Regmir commented
👍

2019-12-05 13:04 UTC, karevboris commented
👍

2019-12-07 19:06 UTC, merged