Лапин -- Лабораторная работа #2
UNN-ITMM-Software/agile-course-practice pull request #80
Opened 2019-11-30 14:06 UTC by Regmir

2019-11-30 14:11 UTC, Regmir commented
@stepanshulpin @karevboris Заревьюйте пожалуйста

2019-12-01 16:18 UTC, karevboris requested changes

2019-12-01 16:18 UTC, karevboris commented on code/mortgage-calculator/ViewModel/src/main/java/ru/unn/agile/MortgageCalculator/viewmodel/ViewModel.java
> +        if (loanPeriod.get().equals("")) {
Я так понял, если res уже false, то дальнейшие проверки не имеют смысла.

2019-12-01 16:18 UTC, karevboris commented on code/mortgage-calculator/ViewModel/src/main/java/ru/unn/agile/MortgageCalculator/viewmodel/ViewModel.java
> +    public void calculate() {
Можно разбить на несколько методов:
- установка параметров
- расчёт в зависимости от условий
- сохранение результата

2019-12-01 16:18 UTC, karevboris commented on settings.gradle
>  // Шульпин Степан
Надо переименовать в mortgage-calculator и новые модули добавить сюда.

2019-12-04 17:30 UTC, stepanshulpin commented on code/mortgage-calculator/ViewModel/src/main/java/ru/unn/agile/MortgageCalculator/viewmodel/ViewModel.java
> +            onInput(newValue);
Ниже есть метод, подразумевающий ввод целочисленных значений. Если бы этот метод назывался onDoubleInput было бы более читаемо

2019-12-04 17:34 UTC, stepanshulpin commented on code/mortgage-calculator/ViewModel/src/main/java/ru/unn/agile/MortgageCalculator/viewmodel/ViewModel.java
> +        if (loanPeriod.get().equals("")) {
вместо переменной res можно сразу делать return

2019-12-04 17:35 UTC, stepanshulpin commented on code/mortgage-calculator/ViewModel/src/main/java/ru/unn/agile/MortgageCalculator/viewmodel/ViewModel.java
> +        if (result.get().equals("Incorrect input")) {
выглядит костылем, напрашивается отдельная булева переменная

2019-12-04 17:38 UTC, stepanshulpin commented on code/mortgage-calculator/ViewModel/src/main/java/ru/unn/agile/MortgageCalculator/viewmodel/ViewModel.java
> +            result.set("Incorrect input");
я думаю, что можно объединить обработку эксепшенов

2019-12-04 17:39 UTC, stepanshulpin commented on code/mortgage-calculator/ViewModel/src/main/java/ru/unn/agile/MortgageCalculator/viewmodel/ViewModel.java
> +        this.result.set(result);
стоит дать разные названия полю и переменной

2019-12-04 19:07 UTC, stepanshulpin commented
👍

2019-12-05 13:01 UTC, karevboris commented
👍

2019-12-07 19:01 UTC, merged