Бевзюк Семен -- Лабораторная работа #2
UNN-ITMM-Software/agile-course-practice pull request #91
Opened 2019-12-07 20:09 UTC by SemyonBevzuk

@Anna-Mironova  @KulyginaJulia
Посмотрите на досуге.

2019-12-08 09:40 UTC, KulyginaJulia commented
👍

2019-12-08 13:05 UTC, Anna-Mironova commented on code/statistics-calculation/ViewModel/src/main/java/ru/unn/agile/StatisticsCalculation/viewmodel/ViewModel.java
> +    }
Значения случайной величины values могут быть не только Integer, а также Double.

2019-12-08 13:58 UTC, SemyonBevzuk commented on code/statistics-calculation/ViewModel/src/main/java/ru/unn/agile/StatisticsCalculation/viewmodel/ViewModel.java
> +    }
Готово

2019-12-08 14:35 UTC, Anna-Mironova commented
👍

2019-12-09 15:24 UTC, VitKonevskiy commented
Make a rebase, pls

2019-12-09 15:25 UTC, VitKonevskiy requested changes

2019-12-09 15:25 UTC, VitKonevskiy commented on code/statistics-calculation/View/src/main/java/ru.unn.agile.StatisticsCalculation.view/Calculator.java
> +package ru.unn.agile.StatisticsCalculation.view;
Use low-case for package naming pls

2019-12-09 17:26 UTC, SemyonBevzuk commented on code/statistics-calculation/View/src/main/java/ru.unn.agile.StatisticsCalculation.view/Calculator.java
> +package ru.unn.agile.StatisticsCalculation.view;
Done

2019-12-10 18:30 UTC, merged