Юферев -- Лабораторная работа #2
UNN-ITMM-Software/agile-course-practice pull request #95
Opened 2019-12-08 20:28 UTC by YuferevKirill

2019-12-08 20:29 UTC, YuferevKirill commented
@Nikita-Mitrokhin, @ksenya-sizova, review second lab please.

2019-12-08 20:36 UTC, Nikita-Mitrokhin commented on code/queue/ViewModel/src/test/java/ru/unn/agile/Queue/viewmodel/ViewModelTests.java
> +
В данном тесте, как и в остальных после этого проверяется статус, но в названии теста это не указано, лучше всего назвать подобные тесты примерно как isStatusPushElementWhenPushElementToQueue и т.д.

2019-12-08 20:46 UTC, YuferevKirill commented on code/queue/ViewModel/src/test/java/ru/unn/agile/Queue/viewmodel/ViewModelTests.java
> +
ok, fixed, thx

2019-12-08 20:47 UTC, ksenya-sizova commented on code/queue/ViewModel/src/main/java/ru/unn/agile/Queue/ViewModel/ViewModel.java
> +        if ("".equals(getQueueElement())) {
Мне кажется, лучше использовать isEmpty() метод для проверки строки на пустоту.

2019-12-08 20:56 UTC, YuferevKirill commented on code/queue/ViewModel/src/main/java/ru/unn/agile/Queue/ViewModel/ViewModel.java
> +        if ("".equals(getQueueElement())) {
thank you, fixed

2019-12-08 21:04 UTC, ksenya-sizova commented
:+1:

2019-12-08 21:21 UTC, Nikita-Mitrokhin commented
:+1:

2019-12-08 22:40 UTC, YuferevKirill commented
@VitKonevskiy

2019-12-09 01:41 UTC, VitKonevskiy requested changes

2019-12-09 01:41 UTC, VitKonevskiy commented on code/queue/View/src/main/java/ru/unn/agile/Queue/view/Main.java
> +package ru.unn.agile.Queue.view;
Use low case for package naming, pls

2019-12-09 01:41 UTC, VitKonevskiy commented on code/queue/View/src/main/java/ru/unn/agile/Queue/view/Queue.java
> +package ru.unn.agile.Queue.view;
Use low case for package naming, pls

2019-12-09 01:41 UTC, VitKonevskiy commented on code/queue/View/src/test/java/ru/unn/agile/Queue/view/FakeViewTests.java
> +package ru.unn.agile.Queue.view;
Use low case for package naming, pls

2019-12-09 06:03 UTC, YuferevKirill commented on code/queue/View/src/main/java/ru/unn/agile/Queue/view/Main.java
> +package ru.unn.agile.Queue.view;
fixed

2019-12-09 06:03 UTC, YuferevKirill commented on code/queue/View/src/main/java/ru/unn/agile/Queue/view/Queue.java
> +package ru.unn.agile.Queue.view;
fixed

2019-12-09 06:04 UTC, YuferevKirill commented on code/queue/View/src/test/java/ru/unn/agile/Queue/view/FakeViewTests.java
> +package ru.unn.agile.Queue.view;
fixed

2019-12-09 14:04 UTC, merged