Красильников -- Лабораторная работа #2
UNN-ITMM-Software/agile-course-practice pull request #96
Opened 2019-12-08 21:34 UTC by NorthlaneKek

Lab2 mvvm matrix

2019-12-08 21:40 UTC, NorthlaneKek commented
@nik709 
@Vagik

2019-12-09 07:22 UTC, nik709 commented on code/kochetova-dasha-lab1-matrix/viewmodel/src/main/java/ru/unn/agile/Matrix/viewmodel/ViewModel.java
> +    public Matrix getFirstMatrix() {
Этот метод используется где-нибдуь?
Если нет, то стоит его удалить.

2019-12-09 07:22 UTC, nik709 commented on code/kochetova-dasha-lab1-matrix/viewmodel/src/main/java/ru/unn/agile/Matrix/viewmodel/ViewModel.java
> +    public void setFirstMatrix(final Matrix firstMatrix) {
Также не нашел нигде использование этого метода

2019-12-09 07:22 UTC, nik709 commented on code/kochetova-dasha-lab1-matrix/viewmodel/src/main/java/ru/unn/agile/Matrix/viewmodel/ViewModel.java
> +    public Matrix getSecondMatrix() {
Тоже не используется?

2019-12-09 07:22 UTC, nik709 commented on code/kochetova-dasha-lab1-matrix/viewmodel/src/main/java/ru/unn/agile/Matrix/viewmodel/ViewModel.java
> +    public void setSecondMatrix(final Matrix secondMatrix) {
Тоже самое

2019-12-09 12:52 UTC, nik709 commented
👍

2019-12-09 18:35 UTC, Vagik commented on code/kochetova-dasha-lab1-matrix/View/src/main/java/ru/unn/agile/Matrix/view/Matrix.java
> +        first00.textProperty().bindBidirectional(viewModel.getFirstMatrixPropertiesByIndex("0"));
Числа 0-8 можно в константы вынести

2019-12-09 18:35 UTC, Vagik commented on code/kochetova-dasha-lab1-matrix/View/src/main/java/ru/unn/agile/Matrix/view/Matrix.java
> +            viewModel.compareMatrices();
Напиши в одну строчку, чтобы один код-стайл был, как ниже

2019-12-09 18:35 UTC, Vagik commented on code/kochetova-dasha-lab1-matrix/viewmodel/src/main/java/ru/unn/agile/Matrix/viewmodel/ViewModel.java
> +        for (i = 0; i < firstMatrixProperties.length; i++) {
Незачем объявлять отдельно переменную. Сделай это в самом цикле

2019-12-09 18:35 UTC, Vagik commented on code/kochetova-dasha-lab1-matrix/viewmodel/src/test/java/ru/unn/agile/Matrix/viewmodel/ViewModelTests.java
> +        assertEquals("", viewModel.getSecondMatrixProperties()[8].get());
Надо бы это дело в один assert оформить

2019-12-11 09:47 UTC, Vagik commented
👍

2019-12-11 09:51 UTC, NorthlaneKek commented
@might52

2019-12-11 14:06 UTC, might52 commented on code/kochetova-dasha-lab1-matrix/viewmodel/build.gradle
> +    compile project(':kochetova-dasha-lab1-matrix-model')
Почему проект называется Кочетова Даша?

Поменяй имена проектов на matrix или любое другое осмысленное название. Соответственно скорректируй нейминг модулей и пакетов.
От "фамилий и имен" отказались. 
Поправь во всех местах.

2019-12-11 14:07 UTC, might52 requested changes
Поменяй имена проектов на matrix или любое другое осмысленное название. Соответственно скорректируй именование модулей и пакетов.
От "фамилий и имен" отказались, то есть наличие в именованиих Кочетовой Даши недопустимо.
Поправь во всех местах.

2019-12-11 16:39 UTC, NorthlaneKek commented
@might52 готово

2019-12-12 14:34 UTC, might52 approved these changes

2019-12-12 14:34 UTC, merged